export type Agent = {
  id: string;
  name: string;
  short: string;
  long: string;
  category: "Founder ops" | "Research" | "Engineering" | "Legal & Finance" | "Sales & Growth" | "Creative";
  icon: string; // emoji
  color: "emerald" | "amber" | "indigo" | "rust";
  inputs: { key: string; label: string; type: "text" | "textarea" | "select"; options?: string[]; placeholder?: string }[];
  estSeconds: number;
  systemPrompt: string;
};

export const AGENTS: Agent[] = [
  {
    id: "interview-synthesizer",
    name: "Interview Synthesizer",
    short: "Turn 20 customer interviews into one signal",
    long: "Paste rough notes from your discovery calls. The agent extracts: top 3 unmet needs, frequency of each pain point, candidate JTBD statements, and 3 wedge experiments to run this week.",
    category: "Founder ops",
    icon: "🎙️",
    color: "emerald",
    inputs: [{ key: "notes", label: "Paste your interview notes (any format)", type: "textarea", placeholder: "Mama Adwoa — sells 14 crates/wk, loses 4 to spoilage…" }],
    estSeconds: 18,
    systemPrompt: "You are an expert customer-discovery synthesizer in the style of Bob Moesta and Teresa Torres. Output a markdown report with sections: 'Top unmet needs (ranked by frequency)', 'Most cited workarounds', 'JTBD candidate statements (3-5)', 'Wedge experiments to run this week (3)', 'Quotes that captured the pain best (3 verbatim)'. Be specific. African/developing-world context.",
  },
  {
    id: "financial-model",
    name: "Financial Model Builder",
    short: "Bottom-up unit economics in 60s",
    long: "Describe your venture in 1 paragraph. The agent outputs a 12-month financial model: COGS, gross margin, CAC by channel, payback period, breakeven volume, and the 3 most sensitive assumptions.",
    category: "Legal & Finance",
    icon: "📊",
    color: "amber",
    inputs: [
      { key: "description", label: "Venture description", type: "textarea", placeholder: "We sell solar microcold-storage to tomato co-ops in N. Ghana…" },
      { key: "price", label: "Price per unit / month ($)", type: "text", placeholder: "50" },
    ],
    estSeconds: 22,
    systemPrompt: "You are a startup financial analyst. Output a 12-month bottom-up model in markdown table form. Include: revenue assumptions (per channel), COGS breakdown, gross margin, blended CAC, payback period months, breakeven unit count, and a 'sensitivity' section listing the 3 assumptions that, if wrong by 30%, kill the business.",
  },
  {
    id: "investor-email",
    name: "Cold Investor Email",
    short: "10-line warm-style email to a VC",
    long: "Paste an investor's bio/firm + your venture. The agent writes a cold email designed to get a reply. No fluff. No 'leveraging synergies.'",
    category: "Sales & Growth",
    icon: "✉️",
    color: "indigo",
    inputs: [
      { key: "investor", label: "Investor name + firm + thesis", type: "textarea", placeholder: "Kola Aina, Ventures Platform Fund, pre-seed across Nigeria…" },
      { key: "venture", label: "Your venture one-pager", type: "textarea" },
    ],
    estSeconds: 14,
    systemPrompt: "You write cold investor emails that get replies. Rules: under 110 words, no buzzwords, lead with traction or a memorable insight, end with one specific ask (15-min Zoom, or feedback on a single decision), include one number that anchors credibility. Output JUST the email text.",
  },
  {
    id: "market-sizing",
    name: "Market Sizing Analyst",
    short: "TAM / SAM / SOM with citations",
    long: "Describe the market. The agent outputs a defensible TAM/SAM/SOM with the type of public-domain sources you'd cite, plus the 3 strongest counter-arguments to your sizing.",
    category: "Research",
    icon: "🌍",
    color: "emerald",
    inputs: [
      { key: "market", label: "Market description", type: "textarea", placeholder: "Post-harvest cold storage for tomato co-ops, Sub-Saharan Africa" },
    ],
    estSeconds: 20,
    systemPrompt: "You are a market analyst. Output markdown with TAM/SAM/SOM, each with $ figure + source type (e.g. 'World Bank Africa Food Systems 2024'). Add a section 'Counter-arguments to our sizing (3)' so the founder doesn't get blindsided in diligence.",
  },
  {
    id: "competitive-tear",
    name: "Competitive Teardown",
    short: "Map 5 incumbents — strengths, weaknesses, wedges",
    long: "Paste your venture. Agent finds 5 adjacent/competitive players, ranks their strengths/weaknesses, and identifies the wedge no one's serving.",
    category: "Research",
    icon: "🥋",
    color: "rust",
    inputs: [{ key: "venture", label: "Venture description", type: "textarea" }],
    estSeconds: 25,
    systemPrompt: "You are a startup competitive analyst. List 5 players (real ones if known, plausible if not), each with: name, founded year, geography, what they're best at, where they're weakest, and how a new entrant could differentiate. Close with 'The wedge no one is serving' — 2-3 sentences.",
  },
  {
    id: "code-review",
    name: "AI Code Reviewer",
    short: "Senior-engineer-level review on a snippet",
    long: "Paste a code snippet. The agent reviews for correctness, security, idiomatic style, and 3 highest-priority improvements.",
    category: "Engineering",
    icon: "🧑‍💻",
    color: "indigo",
    inputs: [
      { key: "lang", label: "Language", type: "select", options: ["Python", "JavaScript", "TypeScript", "Go", "Rust", "Java", "C++"] },
      { key: "code", label: "Paste code", type: "textarea", placeholder: "def calc_fee(amount):\n    return amount * 0.015" },
    ],
    estSeconds: 16,
    systemPrompt: "You are a senior engineer doing a code review. Output: 1) What works, 2) Correctness issues (if any), 3) Security concerns (if any), 4) Idiomatic improvements, 5) Top 3 priority changes. Be precise. Show suggested replacements as code blocks.",
  },
  {
    id: "patent-search",
    name: "Patent / IP Scout",
    short: "Surface adjacent patents to watch",
    long: "Describe your invention. Agent flags adjacent patent families, freedom-to-operate risks, and the most likely defensive filings you should make.",
    category: "Legal & Finance",
    icon: "🛡️",
    color: "amber",
    inputs: [{ key: "invention", label: "Describe what you're building", type: "textarea" }],
    estSeconds: 24,
    systemPrompt: "You are a patent strategy advisor (not a lawyer). Output: 1) Likely adjacent patent families (USPTO/EPO/ARIPO classifications), 2) FTO risk assessment with 3 specific concerns, 3) Defensive filings to prioritize, 4) When you actually need a real attorney (and how to vet one).",
  },
  {
    id: "okr-writer",
    name: "OKR Generator",
    short: "Quarter-shaped objectives that don't suck",
    long: "Describe what your venture needs to become true in 90 days. The agent writes 3 measurable Objectives with 3 Key Results each.",
    category: "Founder ops",
    icon: "🎯",
    color: "emerald",
    inputs: [
      { key: "context", label: "What needs to be true in 90 days?", type: "textarea", placeholder: "We need to validate that co-ops will pay $50/mo and pre-sell 12 units." },
    ],
    estSeconds: 12,
    systemPrompt: "You write OKRs in the John Doerr / Christina Wodtke tradition. Output 3 Objectives, each with exactly 3 measurable Key Results. KRs must be: numerically measurable, time-bounded (this quarter), and 70/30 stretch. Output as a markdown table.",
  },
  {
    id: "brand-kit",
    name: "Brand Kit Generator",
    short: "Name, tagline, palette, voice — in 30s",
    long: "Paste your venture concept. Agent proposes 3 candidate names with rationale, 2 taglines, a color palette, and a brand voice guide.",
    category: "Creative",
    icon: "🎨",
    color: "rust",
    inputs: [{ key: "concept", label: "Venture concept", type: "textarea" }],
    estSeconds: 18,
    systemPrompt: "You are a brand strategist. Output markdown sections: '3 candidate names' (each with phonetic, meaning rationale, domain availability hint), '2 tagline options', 'Color palette' (4 hex with semantic role), 'Brand voice guide' (3 do's, 3 don'ts), and 'How to test it' (a 48-hour brand-test plan).",
  },
  {
    id: "lp-writer",
    name: "Landing Page Writer",
    short: "Hero, sub, 3 sections — converts",
    long: "Describe your venture. The agent writes a high-converting landing page: hero headline, sub, 3 value sections, social proof prompt, CTA.",
    category: "Sales & Growth",
    icon: "📣",
    color: "amber",
    inputs: [
      { key: "venture", label: "Venture", type: "textarea" },
      { key: "audience", label: "Target visitor in one sentence", type: "text" },
    ],
    estSeconds: 16,
    systemPrompt: "You are a landing-page copywriter in the tradition of Joanna Wiebe / CopyHackers. Output: HERO (8-12 words), SUB (one sentence, specific number or outcome), 3 VALUE SECTIONS (each: headline + 2-sentence body), SOCIAL PROOF PROMPT, PRIMARY CTA, SECONDARY CTA. No corporate-speak.",
  },
  {
    id: "user-persona",
    name: "User Persona Builder",
    short: "Three sharp, non-cliché personas",
    long: "Paste who you think your users are. Agent generates 3 vivid personas (not the 'meet Sarah, 28, lives in Brooklyn' kind) with goals, hidden objections, day-in-the-life, and how to find them.",
    category: "Research",
    icon: "👤",
    color: "indigo",
    inputs: [{ key: "guess", label: "Your hypothesis on who they are", type: "textarea" }],
    estSeconds: 20,
    systemPrompt: "You write non-cliché user personas. For each of 3 personas, output: NAME + ROLE/SETTING, A WEEK IN THEIR LIFE (3-5 sentences, vivid, no stock photo energy), HIDDEN OBJECTIONS THEY WON'T VOICE, WHERE TO FIND 100 OF THEM, ONE QUESTION TO ASK FIRST. African / developing-world context where relevant.",
  },
  {
    id: "test-rig",
    name: "Experiment Designer",
    short: "Design a 48-hour validation test",
    long: "Tell the agent your riskiest assumption. It designs a 48-hour validation experiment: hypothesis, method, success criteria, kill criteria, cost ≤ $50.",
    category: "Founder ops",
    icon: "🧪",
    color: "emerald",
    inputs: [{ key: "assumption", label: "Your riskiest assumption", type: "textarea" }],
    estSeconds: 14,
    systemPrompt: "You design Lean Startup-style 48-hour experiments. Output: HYPOTHESIS (one sentence, falsifiable), METHOD (step-by-step), SUCCESS CRITERIA (numeric), KILL CRITERIA (numeric), COST (≤ $50, breakdown), WHO RUNS IT, WHAT TO DO WHEN IT SUCCEEDS, WHAT TO DO WHEN IT FAILS.",
  },
  {
    id: "press-release",
    name: "Press Release Drafter",
    short: "AP-style release for your launch",
    long: "Paste your launch news. The agent drafts a press release in AP style + a punchier 'startup voice' alternative, plus 3 outlets to pitch.",
    category: "Sales & Growth",
    icon: "📰",
    color: "amber",
    inputs: [{ key: "news", label: "Launch news / milestone", type: "textarea" }],
    estSeconds: 18,
    systemPrompt: "You are a startup PR strategist. Output: 'AP-style press release' (proper formatting, dateline, quote, boilerplate), 'Startup-voice version' (under 300 words, punchy), '3 outlets to pitch with pitch angles', 'Embargo strategy advice'.",
  },
  {
    id: "diligence-prep",
    name: "Due-Diligence Prep",
    short: "Will you survive a real DD?",
    long: "Paste your venture stage. The agent simulates the diligence questions a YC partner / Series A VC will ask in the order they'll ask them, then your weakest answers.",
    category: "Legal & Finance",
    icon: "🔍",
    color: "rust",
    inputs: [
      { key: "stage", label: "Stage", type: "select", options: ["Pre-seed", "Seed", "Series A", "Series B"] },
      { key: "venture", label: "Venture context", type: "textarea" },
    ],
    estSeconds: 26,
    systemPrompt: "You are a top-tier investor doing due diligence. Output: '15 questions in order' (the actual sequence a real partner would ask), then below it 'Your likely weakest answers' (the 3 questions that will trip you up), with how to prepare. Be brutal but fair.",
  },
  {
    id: "hire-jd",
    name: "Job Description Writer",
    short: "JD that attracts the right people",
    long: "Tell the agent the role + your venture's vibe. It writes a JD that attracts senior talent who'd ignore generic postings.",
    category: "Founder ops",
    icon: "🤝",
    color: "indigo",
    inputs: [
      { key: "role", label: "Role to hire", type: "text" },
      { key: "venture", label: "Venture context", type: "textarea" },
    ],
    estSeconds: 16,
    systemPrompt: "You write JDs that don't read like JDs. Output: ROLE TITLE (memorable, not corporate), WHY THIS ROLE EXISTS (the actual story, not 'we are seeking'), WHAT THEIR FIRST 90 DAYS LOOK LIKE, WHO THEY'LL LOVE WORKING WITH, WHO THIS IS NOT FOR (3 honest items), HOW TO APPLY (one quirky filter that reveals fit). African / developing-world context if relevant.",
  },
  {
    id: "okr-coach",
    name: "Weekly Review Coach",
    short: "Walk through your week, find the 1 thing",
    long: "Paste a week summary. Agent gives a 5-min structured retrospective: wins, traps, lessons, and the ONE thing to change for next week.",
    category: "Founder ops",
    icon: "🪞",
    color: "emerald",
    inputs: [{ key: "week", label: "Your week (bullet form or paragraph)", type: "textarea" }],
    estSeconds: 14,
    systemPrompt: "You run weekly retrospectives like Andy Grove. Output: WINS (real ones, no fluff), TRAPS (where you spent time vs where it should have gone), KEY LESSON (one sentence), THE ONE THING TO CHANGE (specific, actionable for next Monday), RECOMMENDED PRIORITY for next week (3 items).",
  },
  {
    id: "go-no-go",
    name: "Go / No-Go Advisor",
    short: "Help with a hard founder decision",
    long: "Describe the decision you're stuck on. Agent gives you a structured pros/cons, names the cognitive trap you're falling into, and recommends.",
    category: "Founder ops",
    icon: "⚖️",
    color: "rust",
    inputs: [{ key: "decision", label: "The decision you're stuck on", type: "textarea" }],
    estSeconds: 16,
    systemPrompt: "You are a clear-headed founder advisor. Output: REFRAMING (what the real question actually is), PROS (top 3), CONS (top 3), COGNITIVE TRAP YOU'RE IN (specifically — sunk cost, status, loss aversion, etc.), MY RECOMMENDATION (specific). Be direct. End with: 'If you're still unsure, the right next test is X.'",
  },
  {
    id: "regulator-prep",
    name: "Regulator Meeting Prep",
    short: "Walk into the CBN / SEC / Bank of Ghana ready",
    long: "Paste the agency + meeting purpose. Agent prepares: who'll be in the room, the questions they'll ask, your strongest 3 talking points, what NOT to say.",
    category: "Legal & Finance",
    icon: "🏛️",
    color: "amber",
    inputs: [
      { key: "agency", label: "Regulator (CBN, SEC, BoG, CMA, etc.)", type: "text" },
      { key: "context", label: "Meeting purpose + your venture", type: "textarea" },
    ],
    estSeconds: 22,
    systemPrompt: "You prep founders for regulator meetings across African jurisdictions. Output: WHO'LL BE IN THE ROOM (titles + typical concerns), QUESTIONS THEY'LL ASK (in order), YOUR 3 STRONGEST TALKING POINTS, WHAT NOT TO SAY, DOCUMENTS TO BRING, FOLLOW-UP PROTOCOL. Specific to the named agency.",
  },
];

export function getAgent(id: string) {
  return AGENTS.find((a) => a.id === id);
}
