// Discipline taxonomy modeled on real African university structures (KNUST, UG, UNILAG, UoN, Wits, Makerere, UCT, AAU, etc.).
// Each discipline points to relevant tracks, agents, problem sectors, and AI opportunities.

export type Program = {
  id: string;
  name: string;
  level: "Undergraduate" | "Postgraduate" | "Both";
};

export type Department = {
  id: string;
  name: string;
  programs: Program[];

  // Recommendation mappings
  relevantSectors: string[]; // matches PROBLEMS.sector
  relevantTracks: string[]; // matches TRACKS.id
  relevantAgents: string[]; // matches AGENTS.id
  relevantProblemIds?: string[]; // explicit Problem Hub ids
  relevantMentorExpertise: string[]; // matches Mentor.expertise

  // The 3 most leveraged AI opportunities for this discipline
  aiOpportunities: { title: string; why: string }[];

  // Local-context examples this discipline cares about
  localExamples: string[];

  // Career roles this discipline produces (for placement copy)
  careerRoles: string[];

  // Suggested first venture idea
  suggestedVentureSeed: string;
};

export type School = {
  id: string;
  name: string;
  icon: string;
  color: "emerald" | "amber" | "rust" | "indigo";
  departments: Department[];
};

export const SCHOOLS: School[] = [
  {
    id: "engineering",
    name: "College of Engineering",
    icon: "⚙️",
    color: "indigo",
    departments: [
      {
        id: "agric-eng",
        name: "Agricultural Engineering",
        programs: [
          { id: "bsc-agric", name: "BSc Agricultural Engineering", level: "Undergraduate" },
          { id: "msc-soil-water", name: "MSc Soil & Water Engineering", level: "Postgraduate" },
          { id: "msc-postharvest", name: "MSc Post-harvest Technology", level: "Postgraduate" },
        ],
        relevantSectors: ["Agriculture", "Climate", "Water"],
        relevantTracks: ["stem-intuition", "coding-craft", "ai-for-your-field", "venture-building"],
        relevantAgents: ["market-sizing", "competitive-tear", "financial-model", "test-rig", "interview-synthesizer"],
        relevantProblemIds: ["post-harvest-loss", "climate-adaptation", "water-quality"],
        relevantMentorExpertise: ["Agribusiness", "Food systems", "Impact investing", "Agritech hardware"],
        aiOpportunities: [
          { title: "Vision-based crop disease detection on $50 phones", why: "FastViT/MobileNet now reach senior-agronomist accuracy. Your domain knowledge picks the right disease set." },
          { title: "Solar-powered cold-chain controllers", why: "Embedded ML + power-aware scheduling — your thermo + circuits background is rare and valuable." },
          { title: "Hyperlocal climate forecasting in mother-tongue voice", why: "Combine ag-met models with TTS. Your domain says what farmers actually need to hear." },
        ],
        localExamples: ["Tomato co-op in Tamale losing 4 crates/wk", "Cocoa farmer in Bonsu Nkwanta", "Cassava grower battling mosaic disease in Kogi"],
        careerRoles: ["Field engineer", "Agritech founder", "AGRA program officer", "Food-systems consultant"],
        suggestedVentureSeed: "Solar microcold storage with vision-graded produce sorting for tomato/onion co-ops in your home region.",
      },
      {
        id: "mech-eng",
        name: "Mechanical Engineering",
        programs: [
          { id: "bsc-mech", name: "BSc Mechanical Engineering", level: "Undergraduate" },
          { id: "msc-manufacturing", name: "MSc Manufacturing Systems", level: "Postgraduate" },
          { id: "msc-energy", name: "MSc Energy Systems", level: "Postgraduate" },
        ],
        relevantSectors: ["Energy", "Logistics", "Climate", "Agriculture"],
        relevantTracks: ["stem-intuition", "math-mastery", "ai-for-your-field", "venture-building"],
        relevantAgents: ["financial-model", "test-rig", "patent-search", "competitive-tear", "regulator-prep"],
        relevantProblemIds: ["minigrid-design", "logistics-last-mile", "climate-adaptation"],
        relevantMentorExpertise: ["Off-grid energy", "Agritech hardware", "Engineering culture"],
        aiOpportunities: [
          { title: "AI-orchestrated minigrid design", why: "Satellite + census + load curves → buildable BoM + bankable model in minutes. 100× faster than CAD-by-hand." },
          { title: "Predictive maintenance for boda-boda fleets", why: "Cheap IMU + on-device anomaly detection saves 30%+ in repair costs." },
          { title: "Cold-chain hardware controllers", why: "Embedded systems with power-aware scheduling for off-grid contexts." },
        ],
        localExamples: ["NEPA outage patterns in Aba", "Trotro maintenance economics in Accra", "Rural minigrid in Northern Nigeria"],
        careerRoles: ["Mechanical design engineer", "Energy-systems founder", "Manufacturing operations lead", "Hardware advisor"],
        suggestedVentureSeed: "AI-driven minigrid feasibility tool that turns a satellite image into a deployable spec in 15 minutes.",
      },
      {
        id: "elec-eng",
        name: "Electrical & Electronic Engineering",
        programs: [
          { id: "bsc-eee", name: "BSc Electrical & Electronic Engineering", level: "Undergraduate" },
          { id: "msc-power", name: "MSc Power Systems", level: "Postgraduate" },
          { id: "msc-comms", name: "MSc Communications", level: "Postgraduate" },
        ],
        relevantSectors: ["Energy", "Logistics"],
        relevantTracks: ["stem-intuition", "math-mastery", "coding-craft", "ai-for-your-field"],
        relevantAgents: ["code-review", "patent-search", "financial-model", "test-rig"],
        relevantProblemIds: ["minigrid-design", "water-quality"],
        relevantMentorExpertise: ["Off-grid energy", "Engineering culture", "Open banking"],
        aiOpportunities: [
          { title: "Smart-meter ML for theft detection", why: "Anomaly detection in load curves catches losses utilities currently estimate at 30%." },
          { title: "Low-bandwidth USSD-IoT bridges", why: "When 4G isn't there, 2G+USSD is. Your radio depth is the wedge." },
          { title: "Edge-AI on solar-powered devices", why: "Power-aware inference for off-grid deployments." },
        ],
        localExamples: ["NEPA load shedding in Lagos", "Off-grid clinics in Karamoja", "Tanzanian solar pay-as-you-go"],
        careerRoles: ["Power engineer", "Hardware founder", "Telecoms engineer", "Embedded ML engineer"],
        suggestedVentureSeed: "Pay-as-you-go smart meter that detects theft and shaves 30% off utility losses.",
      },
      {
        id: "civil-eng",
        name: "Civil Engineering",
        programs: [
          { id: "bsc-civil", name: "BSc Civil Engineering", level: "Undergraduate" },
          { id: "msc-structural", name: "MSc Structural Engineering", level: "Postgraduate" },
          { id: "msc-transport", name: "MSc Transportation Engineering", level: "Postgraduate" },
        ],
        relevantSectors: ["Water", "Logistics", "Climate", "Governance"],
        relevantTracks: ["stem-intuition", "math-mastery", "ai-for-your-field"],
        relevantAgents: ["market-sizing", "regulator-prep", "competitive-tear"],
        relevantProblemIds: ["water-quality", "logistics-last-mile", "governance-procurement"],
        relevantMentorExpertise: ["Off-grid energy", "Impact investing"],
        aiOpportunities: [
          { title: "Satellite-based informal settlement mapping", why: "Your geomatics depth + open ML = real input to city planners who currently fly blind." },
          { title: "AI-aided pothole/road-condition triage", why: "Phone-camera + cheap GPS becomes the cheapest road inventory ever." },
          { title: "Water network leak detection from pressure logs", why: "ML on telemetry catches non-revenue water utilities lose 40%+ to." },
        ],
        localExamples: ["Lagos flood drainage", "Kampala potholes", "Nairobi non-revenue water"],
        careerRoles: ["Site engineer", "Urban-tech founder", "Civic-tech engineer", "Infrastructure consultant"],
        suggestedVentureSeed: "Phone-camera-based road inventory app for African municipalities — 1/100th the cost of consultant surveys.",
      },
      {
        id: "cse",
        name: "Computer Science & Engineering",
        programs: [
          { id: "bsc-cs", name: "BSc Computer Science", level: "Undergraduate" },
          { id: "msc-ai", name: "MSc Artificial Intelligence", level: "Postgraduate" },
          { id: "msc-software", name: "MSc Software Engineering", level: "Postgraduate" },
        ],
        relevantSectors: ["Finance", "Health", "Education", "Logistics", "Governance"],
        relevantTracks: ["coding-craft", "math-mastery", "ai-for-your-field", "venture-building"],
        relevantAgents: ["code-review", "patent-search", "interview-synthesizer", "user-persona", "lp-writer", "test-rig"],
        relevantProblemIds: ["smb-bookkeeping", "vernacular-tutoring", "credential-trust", "logistics-last-mile"],
        relevantMentorExpertise: ["Fintech", "Engineering culture", "AI/ML", "Open banking", "Marketplace"],
        aiOpportunities: [
          { title: "Foundation models in low-resource African languages", why: "Twi, Yoruba, Hausa, Swahili. The frontier is wide open — Lelapa, Awarri are just starting." },
          { title: "Voice-first SME bookkeeping over WhatsApp", why: "44M unbanked SMEs. Conversation-as-OS bypasses literacy + UX friction." },
          { title: "Verifiable, on-chain skill credentials", why: "Employers don't trust African certificates. Cryptographic + portfolio-anchored fixes this." },
        ],
        localExamples: ["Pidgin-speaking trader in Lagos", "Swahili-only farmer in Dodoma", "Multilingual call-center QA"],
        careerRoles: ["Software engineer", "ML engineer", "Founder/CTO", "Open-source contributor"],
        suggestedVentureSeed: "WhatsApp voice-bot in Pidgin/Swahili that does double-entry bookkeeping for street vendors.",
      },
      {
        id: "chem-eng",
        name: "Chemical Engineering",
        programs: [
          { id: "bsc-chem-eng", name: "BSc Chemical Engineering", level: "Undergraduate" },
          { id: "msc-process", name: "MSc Process Engineering", level: "Postgraduate" },
        ],
        relevantSectors: ["Energy", "Climate", "Health"],
        relevantTracks: ["stem-intuition", "ai-for-your-field", "venture-building"],
        relevantAgents: ["financial-model", "test-rig", "competitive-tear"],
        relevantProblemIds: ["climate-adaptation", "water-quality"],
        relevantMentorExpertise: ["Process engineering", "Energy", "Manufacturing"],
        aiOpportunities: [
          { title: "Process-optimization for small-scale palm-oil + shea processors", why: "Most West African processing operates 30-40% below yield; sensor + ML retrofits pay back in months." },
          { title: "Water-treatment dosing controllers tuned to local raw-water quality", why: "Plants overdose chemicals as a safety margin; ML closes the loop and cuts opex 25%." },
          { title: "Biogas digester monitoring for institutional kitchens", why: "Schools + hospitals generate enough waste to self-power kitchens; controllers make it reliable." },
        ],
        localExamples: ["Palm-oil processor in Kogi running below yield", "Borehole treatment in Mombasa", "Brewery in Kampala optimizing CIP cycles"],
        careerRoles: ["Process engineer", "Plant manager", "Cleantech founder", "QA/QC engineer"],
        suggestedVentureSeed: "IoT yield-optimizer kit for small-scale palm-oil mills with a $/tonne savings-share business model.",
      },
      {
        id: "biomed-eng",
        name: "Biomedical Engineering",
        programs: [
          { id: "bsc-biomed", name: "BSc Biomedical Engineering", level: "Undergraduate" },
          { id: "msc-medtech", name: "MSc Medical Technology", level: "Postgraduate" },
        ],
        relevantSectors: ["Health"],
        relevantTracks: ["stem-intuition", "ai-for-your-field", "coding-craft", "venture-building"],
        relevantAgents: ["test-rig", "regulator-prep", "financial-model"],
        relevantProblemIds: ["chw-diagnostics"],
        relevantMentorExpertise: ["Medical devices", "Hardware", "Regulatory navigation"],
        aiOpportunities: [
          { title: "Low-cost ultrasound for community midwives with AI guidance", why: "Butterfly-style probes + on-phone inference let a CHW catch placental-abnormality cases that today travel 4 hours." },
          { title: "Wearable jaundice monitoring for neonates in rural clinics", why: "Bilirubin estimation from phone-camera + flash works at clinically useful accuracy; deploys today." },
          { title: "Phone-microphone-based pneumonia screening for under-fives", why: "Cough-classification models trained on local data outperform pulse-ox triage in low-resource settings." },
        ],
        localExamples: ["Midwife in Bunia, DRC, with no ultrasound access", "Neonatal jaundice screening at a Kumasi clinic", "Under-five pneumonia triage in Kilifi"],
        careerRoles: ["Medical-device engineer", "Healthtech founder", "Clinical applications specialist", "Regulatory affairs"],
        suggestedVentureSeed: "$80 ultrasound probe + on-phone AI guidance kit for community midwives, sold to ministries of health.",
      },
      {
        id: "petroleum-mining",
        name: "Petroleum & Mining Engineering",
        programs: [
          { id: "bsc-pet", name: "BSc Petroleum Engineering", level: "Undergraduate" },
          { id: "bsc-mining", name: "BSc Mining Engineering", level: "Undergraduate" },
          { id: "msc-energy-trans", name: "MSc Energy Transitions", level: "Postgraduate" },
        ],
        relevantSectors: ["Energy", "Climate"],
        relevantTracks: ["stem-intuition", "ai-for-your-field", "venture-building"],
        relevantAgents: ["financial-model", "competitive-tear", "test-rig"],
        relevantProblemIds: ["climate-adaptation"],
        relevantMentorExpertise: ["Energy", "Extractives", "Impact investing"],
        aiOpportunities: [
          { title: "Artisanal-mining safety + yield monitoring", why: "ASM in DRC/Ghana loses lives weekly to predictable hazards; phone-based gas + slope monitoring saves them." },
          { title: "Geological survey assistant from satellite + drone imagery", why: "Junior geologists can cover 10x more ground when ML pre-flags zones of interest." },
          { title: "Energy-transition planning tool for oil-economy graduates", why: "Nigeria + Angola + Ghana need 10-year reskilling roadmaps; a data-driven planner is institutional gold." },
        ],
        localExamples: ["Galamsey safety in Western Region, Ghana", "Cobalt artisanal mining in Lualaba, DRC", "Niger Delta oil-spill remediation"],
        careerRoles: ["Petroleum engineer", "Mining engineer", "Energy transition consultant", "Extractives-focused founder"],
        suggestedVentureSeed: "Phone-based artisanal-mining safety monitor with text-message hazard alerts, sold to cooperatives + ministries.",
      },
      {
        id: "industrial-eng",
        name: "Industrial & Manufacturing Engineering",
        programs: [
          { id: "bsc-ind", name: "BSc Industrial Engineering", level: "Undergraduate" },
          { id: "msc-supply", name: "MSc Supply Chain Engineering", level: "Postgraduate" },
        ],
        relevantSectors: ["Logistics", "Agriculture"],
        relevantTracks: ["stem-intuition", "ai-for-your-field", "venture-building"],
        relevantAgents: ["financial-model", "interview-synthesizer", "competitive-tear"],
        relevantProblemIds: ["post-harvest-loss"],
        relevantMentorExpertise: ["Manufacturing", "Supply chain", "Logistics"],
        aiOpportunities: [
          { title: "Demand-forecasting for African FMCG distributors", why: "Most distributors use rolling averages; even basic ARIMA + holiday calendars cuts stockouts 30%." },
          { title: "Lean-manufacturing audit-in-a-box for SME factories", why: "Most SME factories have never had a Six Sigma walk-through; a guided self-audit + AI suggestions delivers consultancy-grade output." },
          { title: "Cross-border trade-route optimizer for AfCFTA freight", why: "Customs delays compound costs; ML on past clearance times picks the route + corridor that actually moves fastest." },
        ],
        localExamples: ["Sachet-water plant in Kumasi managing 24/7 shifts", "Coca-Cola bottler in Mombasa improving OEE", "Cement distributor in Dar es Salaam"],
        careerRoles: ["Industrial engineer", "Operations manager", "Supply-chain founder", "Manufacturing consultant"],
        suggestedVentureSeed: "SaaS demand-forecaster for African FMCG distributors, integrating M-Pesa/POS data, $/SKU/month pricing.",
      },
    ],
  },
  {
    id: "health",
    name: "School of Medicine & Health Sciences",
    icon: "🩺",
    color: "rust",
    departments: [
      {
        id: "medicine",
        name: "Medicine & Surgery",
        programs: [
          { id: "mbchb", name: "MBChB / MBBS", level: "Undergraduate" },
          { id: "md", name: "MD / Specialty Residency", level: "Postgraduate" },
        ],
        relevantSectors: ["Health"],
        relevantTracks: ["ai-for-your-field", "venture-building"],
        relevantAgents: ["interview-synthesizer", "regulator-prep", "test-rig", "diligence-prep"],
        relevantProblemIds: ["diagnosis-gap", "vernacular-tutoring"],
        relevantMentorExpertise: ["Healthtech", "Public-sector", "Medical AI"],
        aiOpportunities: [
          { title: "Multimodal AI for community health workers", why: "Photo+voice triage on a $50 phone. Your clinical judgment trains the right ground truth." },
          { title: "Maternal mortality early-warning", why: "375 maternal deaths per 100k in SSA. Wearable + AI risk scores during pregnancy save lives." },
          { title: "TB / malaria image-based screening", why: "Phone-camera microscopy + ML matches senior microbiologist accuracy in studies." },
        ],
        localExamples: ["Rural CHW in Karamoja", "Maternal ward in Mulago", "Misdiagnosed malaria in Edo state"],
        careerRoles: ["Clinician", "Public health official", "Healthtech founder", "Medical AI engineer"],
        suggestedVentureSeed: "Voice-driven triage co-pilot for CHWs in your home region, trained on local disease patterns.",
      },
      {
        id: "pharmacy",
        name: "Pharmacy",
        programs: [
          { id: "pharmd", name: "PharmD / BPharm", level: "Undergraduate" },
          { id: "msc-pharm", name: "MSc Clinical Pharmacy", level: "Postgraduate" },
        ],
        relevantSectors: ["Health", "Logistics"],
        relevantTracks: ["ai-for-your-field", "venture-building"],
        relevantAgents: ["competitive-tear", "regulator-prep", "test-rig"],
        relevantProblemIds: ["diagnosis-gap"],
        relevantMentorExpertise: ["Healthtech", "Supply chain"],
        aiOpportunities: [
          { title: "Counterfeit drug detection via packaging vision", why: "30% of African meds are counterfeit. Phone-camera detection scales fast." },
          { title: "Drug-interaction checker in local languages", why: "Polypharmacy errors kill. Voice-driven check at the chemist counter saves lives." },
          { title: "Cold-chain integrity monitoring for vaccines", why: "Last-mile temperature breaches are the silent killer of immunization programs." },
        ],
        localExamples: ["Patent medicine vendor in Aba", "Vaccine cold-chain in Yaoundé", "Polypharmacy at Korle-Bu"],
        careerRoles: ["Clinical pharmacist", "Pharmacovigilance lead", "Pharma founder", "Regulatory affairs"],
        suggestedVentureSeed: "Counterfeit-drug detection app for patent medicine vendors — scan packaging, get a verdict.",
      },
      {
        id: "public-health",
        name: "Public Health & Epidemiology",
        programs: [
          { id: "bsph", name: "BSc Public Health", level: "Undergraduate" },
          { id: "mph", name: "Master of Public Health", level: "Postgraduate" },
          { id: "phd-epi", name: "PhD Epidemiology", level: "Postgraduate" },
        ],
        relevantSectors: ["Health", "Water", "Governance"],
        relevantTracks: ["math-mastery", "coding-craft", "ai-for-your-field", "venture-building"],
        relevantAgents: ["market-sizing", "regulator-prep", "competitive-tear"],
        relevantProblemIds: ["diagnosis-gap", "water-quality"],
        relevantMentorExpertise: ["Healthtech", "Public-sector", "Climate policy"],
        aiOpportunities: [
          { title: "Outbreak prediction from telco+mobility data", why: "Anonymized phone data + ML beats CDC-style surveillance in low-resource settings." },
          { title: "WaSH risk maps from satellite + field reporting", why: "Where to put the next borehole becomes a data question, not a politics question." },
          { title: "Wearable AI for chronic-disease management", why: "$50 BP cuff + ML coach beats 1 cardiologist per 100k catchment." },
        ],
        localExamples: ["Cholera outbreak in Lusaka", "NCD burden in Cape Town townships", "Vaccine hesitancy in Kano"],
        careerRoles: ["Epidemiologist", "Program officer", "Health-data scientist", "Healthtech founder"],
        suggestedVentureSeed: "Outbreak-warning dashboard for district health officers, fed by anonymized mobility + clinic reports.",
      },
      {
        id: "nursing",
        name: "Nursing & Midwifery",
        programs: [
          { id: "bsn", name: "BSc Nursing", level: "Undergraduate" },
          { id: "msn", name: "MSc Advanced Practice Nursing", level: "Postgraduate" },
        ],
        relevantSectors: ["Health"],
        relevantTracks: ["ai-for-your-field", "venture-building"],
        relevantAgents: ["interview-synthesizer", "test-rig", "user-persona"],
        relevantProblemIds: ["diagnosis-gap"],
        relevantMentorExpertise: ["Healthtech"],
        aiOpportunities: [
          { title: "Maternal monitoring decision-support", why: "Nurse-midwives at the frontlines. Voice-driven CTG interpretation saves babies." },
          { title: "Discharge-planning AI for understaffed wards", why: "Cuts re-admission and frees nurses for direct care." },
          { title: "Trauma triage assistant for rural emergency rooms", why: "Your clinical pattern recognition + AI = consistent triage with zero training overhead." },
        ],
        localExamples: ["Maternal ward in Bugando", "Trauma bay in JOSH", "Community nurse in Wakiso"],
        careerRoles: ["Clinical nurse", "Nurse-leader founder", "Public health officer", "Healthtech product manager"],
        suggestedVentureSeed: "Voice-driven CTG (fetal monitor) interpreter for maternity wards run by midwives.",
      },
      {
        id: "dentistry",
        name: "Dentistry",
        programs: [
          { id: "bds", name: "BDS / Bachelor of Dental Surgery", level: "Undergraduate" },
          { id: "msc-ortho", name: "MSc Orthodontics", level: "Postgraduate" },
        ],
        relevantSectors: ["Health"],
        relevantTracks: ["ai-for-your-field", "venture-building"],
        relevantAgents: ["test-rig", "user-persona", "interview-synthesizer"],
        relevantProblemIds: ["chw-diagnostics"],
        relevantMentorExpertise: ["Medical devices", "Clinical practice"],
        aiOpportunities: [
          { title: "Phone-camera caries screening for school dental programs", why: "Mass screenings cost ~$8/child today; a phone classifier brings it under $0.50 and unlocks public-health programs." },
          { title: "Tele-dentistry triage to flag referrals from rural clinics", why: "1 dentist per 100k people in rural East Africa; image triage routes the urgent cases first." },
          { title: "Affordable 3D scanning workflow for clear aligners", why: "Clear-aligner demand exists in African cities; a local-lab + scanner workflow undercuts Invisalign 70%." },
        ],
        localExamples: ["School dental screening in Kibera", "Rural referral triage from Tamale", "Aligner production lab in Lagos"],
        careerRoles: ["Dentist", "Dental-tech founder", "Public health officer", "Clinical educator"],
        suggestedVentureSeed: "Phone-camera caries pre-screen tool licensed to school health programs at $0.50/child.",
      },
      {
        id: "med-lab",
        name: "Medical Laboratory Sciences",
        programs: [
          { id: "bmls", name: "BSc Medical Laboratory Sciences", level: "Undergraduate" },
          { id: "msc-mls", name: "MSc Clinical Diagnostics", level: "Postgraduate" },
        ],
        relevantSectors: ["Health"],
        relevantTracks: ["ai-for-your-field", "venture-building"],
        relevantAgents: ["test-rig", "regulator-prep", "financial-model"],
        relevantProblemIds: ["chw-diagnostics"],
        relevantMentorExpertise: ["Medical devices", "Diagnostics", "Public health"],
        aiOpportunities: [
          { title: "AI microscopy for malaria + TB + sickle-cell at district labs", why: "Trained technicians are scarce; vision models hit lab-grade accuracy at half the throughput cost." },
          { title: "Quality-control automation for blood-bank operations", why: "Cross-matching + storage QC errors are leading causes of transfusion incidents; sensor + ML catches them." },
          { title: "Specimen-routing optimization for hub-and-spoke lab networks", why: "Most district labs run blind on courier timing; a routing tool cuts result-turnaround by half." },
        ],
        localExamples: ["Malaria microscopy in Bo, Sierra Leone", "Blood-bank QC in Nairobi", "TB sputum-testing hub in Soweto"],
        careerRoles: ["Clinical lab scientist", "Diagnostics founder", "Lab quality manager", "Public-health researcher"],
        suggestedVentureSeed: "AI microscopy assistant for malaria slides — sold to ministries of health at per-slide pricing.",
      },
      {
        id: "physiotherapy",
        name: "Physiotherapy & Rehabilitation",
        programs: [
          { id: "bsc-physio", name: "BSc Physiotherapy", level: "Undergraduate" },
          { id: "msc-rehab", name: "MSc Rehabilitation Science", level: "Postgraduate" },
        ],
        relevantSectors: ["Health"],
        relevantTracks: ["ai-for-your-field", "venture-building"],
        relevantAgents: ["user-persona", "interview-synthesizer", "test-rig"],
        relevantProblemIds: [],
        relevantMentorExpertise: ["Clinical practice", "Sports science"],
        aiOpportunities: [
          { title: "Phone-camera gait analysis for stroke-rehab patients", why: "Patients leave hospital with a printout; a daily app-based check keeps them on protocol and flags regression." },
          { title: "Tele-rehab program library scaled to a single physio", why: "1 physio: 30+ patients ratio is normal; structured programs + AI form-feedback let one clinician serve all of them." },
          { title: "Posture screening for office workers in African cities", why: "Cities like Lagos + Nairobi see a wave of WFH back pain; phone-based screening + structured exercises is a B2C opportunity." },
        ],
        localExamples: ["Stroke recovery in Kampala", "Sports-injury clinic in Accra", "Office-worker posture program in Lagos"],
        careerRoles: ["Clinical physiotherapist", "Sports physio", "Rehab clinic founder", "Digital health PM"],
        suggestedVentureSeed: "Stroke-rehab phone app with daily gait check, sold to clinics at $5/patient/month.",
      },
    ],
  },
  {
    id: "business",
    name: "School of Business & Economics",
    icon: "💼",
    color: "amber",
    departments: [
      {
        id: "finance",
        name: "Finance & Banking",
        programs: [
          { id: "bba-fin", name: "BBA / BCom Finance", level: "Undergraduate" },
          { id: "msc-fin", name: "MSc Finance", level: "Postgraduate" },
          { id: "mba", name: "MBA", level: "Postgraduate" },
        ],
        relevantSectors: ["Finance"],
        relevantTracks: ["math-mastery", "coding-craft", "ai-for-your-field", "venture-building"],
        relevantAgents: ["financial-model", "diligence-prep", "investor-email", "market-sizing"],
        relevantProblemIds: ["smb-bookkeeping", "credential-trust"],
        relevantMentorExpertise: ["Fintech", "Series A-C fundraising", "Series B-C fundraising", "Mobile money"],
        aiOpportunities: [
          { title: "Alternative credit scoring from M-Pesa flows", why: "44M unbanked SMEs. Behavioral data > bureaus that don't have them." },
          { title: "Cross-border FX hedging for diaspora flows", why: "Volatility eats remittance value. ML-driven netting saves billions." },
          { title: "Automated KYC for low-literacy users via voice", why: "Account opening at the speed of conversation in Pidgin/Swahili." },
        ],
        localExamples: ["M-Pesa agent in Kibera", "Hairdresser-microloan in Tema", "Diaspora remittance to Bulawayo"],
        careerRoles: ["Investment analyst", "Fintech founder", "VC associate", "Risk manager"],
        suggestedVentureSeed: "Behavioral credit-scoring engine for African mobile-money SMEs.",
      },
      {
        id: "marketing",
        name: "Marketing & Sales",
        programs: [
          { id: "bba-mkt", name: "BBA Marketing", level: "Undergraduate" },
          { id: "msc-mkt", name: "MSc Marketing Analytics", level: "Postgraduate" },
        ],
        relevantSectors: ["Finance", "Creative", "Logistics"],
        relevantTracks: ["coding-craft", "ai-for-your-field", "venture-building"],
        relevantAgents: ["lp-writer", "user-persona", "press-release", "brand-kit"],
        relevantProblemIds: ["creative-monetization", "smb-bookkeeping"],
        relevantMentorExpertise: ["Marketplace dynamics", "Talent platforms"],
        aiOpportunities: [
          { title: "Multilingual content engines for African creators", why: "Translate + adapt with cultural nuance. Your marketing instinct picks what travels." },
          { title: "WhatsApp commerce automation", why: "B2C in Africa starts on WhatsApp. Conversational checkout and re-engagement are gold." },
          { title: "Influencer-fraud detection", why: "Brands burn millions on bot-padded creators. ML on engagement timing reveals fakes." },
        ],
        localExamples: ["Tomato-seller WhatsApp catalog", "Afrobeats music distribution", "FMCG brand entering Lusaka"],
        careerRoles: ["Brand manager", "Growth marketer", "Marketplace founder", "Creator-economy operator"],
        suggestedVentureSeed: "WhatsApp commerce stack for African D2C brands — catalog, checkout, fulfillment in one bot.",
      },
      {
        id: "economics",
        name: "Economics & Development Studies",
        programs: [
          { id: "ba-econ", name: "BA Economics", level: "Undergraduate" },
          { id: "msc-dev-econ", name: "MSc Development Economics", level: "Postgraduate" },
          { id: "phd-econ", name: "PhD Economics", level: "Postgraduate" },
        ],
        relevantSectors: ["Finance", "Governance", "Agriculture"],
        relevantTracks: ["math-mastery", "coding-craft", "ai-for-your-field"],
        relevantAgents: ["market-sizing", "competitive-tear", "go-no-go"],
        relevantProblemIds: ["governance-procurement", "smb-bookkeeping", "climate-adaptation"],
        relevantMentorExpertise: ["Impact investing", "Climate policy"],
        aiOpportunities: [
          { title: "Real-time economic indicators from satellite + receipts", why: "Africa's GDP is famously mismeasured. Alt-data closes the gap." },
          { title: "Causal-inference tooling for policy experiments", why: "Most African policy is untested. Cheap experimentation tools democratize evidence." },
          { title: "Cash-transfer targeting via mobile-data signatures", why: "GiveDirectly is just the start. ML beats geographic blanket-targeting." },
        ],
        localExamples: ["Cash transfers in Turkana", "Free-trade impact in Kigali", "Inflation in Khartoum"],
        careerRoles: ["Economist", "Policy advisor", "Impact-fund analyst", "Research-to-policy founder"],
        suggestedVentureSeed: "Satellite-based real-time GDP nowcasting service for African finance ministries.",
      },
      {
        id: "accounting",
        name: "Accounting & Audit",
        programs: [
          { id: "bsc-acc", name: "BSc Accounting", level: "Undergraduate" },
          { id: "aca", name: "ICAN / ACCA / CA", level: "Postgraduate" },
          { id: "msc-audit", name: "MSc Audit & Assurance", level: "Postgraduate" },
        ],
        relevantSectors: ["Finance", "Governance"],
        relevantTracks: ["venture-building", "ai-for-your-field"],
        relevantAgents: ["financial-model", "diligence-prep", "regulator-prep"],
        relevantProblemIds: ["credential-trust", "governance-procurement"],
        relevantMentorExpertise: ["Finance", "Audit", "Tax"],
        aiOpportunities: [
          { title: "Mobile-money + POS-receipt to bookkeeping automation", why: "Millions of African SMEs run cash + M-Pesa with no books; auto-categorization unlocks loans + tax compliance." },
          { title: "Audit anomaly detection for cooperatives + savings groups", why: "VSLA-style groups need lightweight audit; ML on transaction patterns flags drift cheaply." },
          { title: "Tax-filing assistant for sole-proprietors in 5 countries", why: "Most informal traders never file; a guided + automated tool brings them into formal economy." },
        ],
        localExamples: ["VSLA in Nakuru tracking weekly contributions", "Kumasi trader using M-Pesa + Vodafone Cash", "Lagos SME doing first audited financials"],
        careerRoles: ["Chartered accountant", "Internal auditor", "Fintech founder", "Tax consultant"],
        suggestedVentureSeed: "M-Pesa + Opay receipt-parser that auto-builds books + tax-return for African micro-traders at $5/month.",
      },
      {
        id: "management",
        name: "Management & Operations",
        programs: [
          { id: "bba-mgt", name: "BBA Management", level: "Undergraduate" },
          { id: "msc-ops", name: "MSc Operations Management", level: "Postgraduate" },
          { id: "exec-mba", name: "Executive MBA", level: "Postgraduate" },
        ],
        relevantSectors: ["Logistics", "Finance"],
        relevantTracks: ["venture-building", "ai-for-your-field"],
        relevantAgents: ["interview-synthesizer", "financial-model", "competitive-tear"],
        relevantProblemIds: ["governance-procurement"],
        relevantMentorExpertise: ["Operations", "General management", "Consulting"],
        aiOpportunities: [
          { title: "Standard-Operating-Procedure generator for African SMEs", why: "Most SMEs scale into chaos because nothing is written down; AI-drafted SOPs from a 20-question intake change the trajectory." },
          { title: "Hiring + interview-rubric tooling for first-time managers", why: "Founders make their first bad hires for predictable reasons; structured rubrics + AI screening cuts that loss." },
          { title: "Performance-management dashboards built on WhatsApp check-ins", why: "African teams already coordinate on WhatsApp; structured weekly check-ins → dashboard is the lightest lift." },
        ],
        localExamples: ["Family-owned distributor in Tema scaling from 5 → 20 staff", "Kenyan logistics SME standardizing dispatch", "Lagos call-center launching with weekly OKRs"],
        careerRoles: ["Operations manager", "Management consultant", "COO-track", "Startup ops lead"],
        suggestedVentureSeed: "SOP-from-conversation tool — talk to it for 20 minutes, get a written ops manual back, $99 one-time.",
      },
      {
        id: "entrepreneurship",
        name: "Entrepreneurship & Innovation",
        programs: [
          { id: "bba-ent", name: "BBA Entrepreneurship", level: "Undergraduate" },
          { id: "msc-inno", name: "MSc Innovation Management", level: "Postgraduate" },
        ],
        relevantSectors: ["Finance"],
        relevantTracks: ["venture-building", "ai-for-your-field", "coding-craft"],
        relevantAgents: ["interview-synthesizer", "competitive-tear", "financial-model", "user-persona"],
        relevantProblemIds: ["credential-trust", "post-harvest-loss"],
        relevantMentorExpertise: ["Venture capital", "Founder coaching", "Impact investing"],
        aiOpportunities: [
          { title: "Founder-grade due-diligence prep tools for first-time fundraisers", why: "Half of African seed rounds collapse at DD because data rooms are messy; AI-organized rooms move deals faster." },
          { title: "Pitch-deck localization for African investor preferences", why: "Pitch decks templated on YC formats miss what African investors want (path to profit > growth); localized templates land better." },
          { title: "Investor-discovery engine matching founders to actually-active funds", why: "Crunchbase data on Africa is stale; a maintained map of active investors saves months of cold-emailing." },
        ],
        localExamples: ["First-time founder in Lagos preparing for pre-seed DD", "Kenyan agritech matching to AgFunder-active investors", "Accra founder writing pitch deck for African angels"],
        careerRoles: ["Founder", "Venture builder", "Accelerator program lead", "Innovation consultant"],
        suggestedVentureSeed: "Founder-readiness toolkit (DD checklist + pitch coach + investor matchmaker) for African pre-seed, $99/month.",
      },
    ],
  },
  {
    id: "law",
    name: "School of Law",
    icon: "⚖️",
    color: "indigo",
    departments: [
      {
        id: "law",
        name: "Law",
        programs: [
          { id: "llb", name: "LLB", level: "Undergraduate" },
          { id: "llm", name: "LLM", level: "Postgraduate" },
          { id: "phd-law", name: "PhD / SJD Law", level: "Postgraduate" },
        ],
        relevantSectors: ["Governance", "Finance"],
        relevantTracks: ["ai-for-your-field", "venture-building"],
        relevantAgents: ["regulator-prep", "patent-search", "diligence-prep"],
        relevantProblemIds: ["governance-procurement", "vernacular-tutoring", "credential-trust"],
        relevantMentorExpertise: ["Digital policy", "Regulatory navigation", "Public-sector"],
        aiOpportunities: [
          { title: "Multilingual legal triage bots", why: "Access to justice in Twi/Hausa/Yoruba where 1 lawyer serves 30k+ people." },
          { title: "Contract review and redlining in seconds", why: "Junior-associate-level review at sub-$1/contract opens a giant SME market." },
          { title: "Case-law RAG with African jurisprudence", why: "Existing tools cite US/UK cases. The continent needs its own corpus surfaced." },
        ],
        localExamples: ["Tenant dispute in Maputo", "Land claim in Kakuma", "Small-claims dispute in Tema"],
        careerRoles: ["Litigation associate", "Legaltech founder", "Public-interest lawyer", "Compliance officer"],
        suggestedVentureSeed: "Twi/Pidgin legal-triage chatbot that tells a citizen what their rights are and where to go.",
      },
      {
        id: "commercial-law",
        name: "Commercial & Corporate Law",
        programs: [
          { id: "llb-comm", name: "LLB (Commercial focus)", level: "Undergraduate" },
          { id: "llm-corp", name: "LLM Corporate Law", level: "Postgraduate" },
        ],
        relevantSectors: ["Finance", "Governance"],
        relevantTracks: ["venture-building", "ai-for-your-field"],
        relevantAgents: ["regulator-prep", "diligence-prep", "financial-model"],
        relevantProblemIds: ["governance-procurement", "credential-trust"],
        relevantMentorExpertise: ["Corporate law", "M&A", "Securities", "Startup law"],
        aiOpportunities: [
          { title: "Term-sheet review and redlining for African founders", why: "Most early-stage African founders sign US-templated SAFEs with bad regional clauses. Automated review catches the trap clauses." },
          { title: "Cap-table + ESOP modeling for first-time founders", why: "Dilution arithmetic is opaque; a guided tool with local tax overlays prevents avoidable lifetime loss." },
          { title: "Cross-border contract translation with legal-validity flags", why: "Most SMEs trade across 2-3 jurisdictions; assistive review at sub-$10/contract opens the SME tier." },
        ],
        localExamples: ["Lagos SaaS founder negotiating a Delaware C-corp", "Nairobi import/export trader's 6-month contract dispute", "Kumasi cooperative incorporating as a limited company"],
        careerRoles: ["Corporate associate", "Startup lawyer", "In-house counsel", "Investment compliance officer"],
        suggestedVentureSeed: "AI-assisted contract & cap-table reviewer scoped to African startup law, with $/month pricing instead of $/hour.",
      },
      {
        id: "public-law",
        name: "Constitutional & Public Law",
        programs: [
          { id: "llb-pub", name: "LLB (Public focus)", level: "Undergraduate" },
          { id: "llm-const", name: "LLM Constitutional Law", level: "Postgraduate" },
        ],
        relevantSectors: ["Governance"],
        relevantTracks: ["ai-for-your-field", "venture-building"],
        relevantAgents: ["regulator-prep"],
        relevantProblemIds: ["governance-procurement", "credential-trust"],
        relevantMentorExpertise: ["Public-sector", "Constitutional law", "Human rights"],
        aiOpportunities: [
          { title: "Citizen-rights bot in mother tongue for police-stop scenarios", why: "Most citizens don't know their rights at a checkpoint. A 30-second WhatsApp answer scales access to justice." },
          { title: "Public-records FOI templating + tracking for journalists", why: "African newsrooms rarely file FOIs at scale; templated requests + deadline tracking change the accountability calculus." },
          { title: "Parliamentary-bill summarizer + impact-on-you assistant", why: "Bills are passed without civic input largely because they're unreadable. Plain-language summaries enable participation." },
        ],
        localExamples: ["Stop-and-search rights in Lagos", "Election-petition timeline in Accra", "FOI request to a district assembly in Cape Coast"],
        careerRoles: ["Public-interest litigator", "Policy advisor", "Constitutional researcher", "Civic-tech founder"],
        suggestedVentureSeed: "Multilingual 'know-your-rights' bot tied to your specific country's constitution, with WhatsApp + USSD delivery.",
      },
      {
        id: "ip-law",
        name: "Intellectual Property & Tech Law",
        programs: [
          { id: "llb-ip", name: "LLB (IP focus)", level: "Undergraduate" },
          { id: "llm-ip", name: "LLM IP & Technology", level: "Postgraduate" },
        ],
        relevantSectors: ["Finance", "Governance"],
        relevantTracks: ["ai-for-your-field", "venture-building", "coding-craft"],
        relevantAgents: ["patent-search", "regulator-prep", "diligence-prep"],
        relevantProblemIds: ["credential-trust"],
        relevantMentorExpertise: ["IP law", "Tech regulation", "Data protection"],
        aiOpportunities: [
          { title: "Prior-art search for African inventors using regional patent corpora", why: "ARIPO + OAPI filings are under-indexed; a search tool that knows them prevents costly duplicate applications." },
          { title: "GDPR / NDPR / POPIA compliance checker for new SaaS products", why: "Every African SaaS launches into a fragmented data-protection regime; rule-driven checklists with redline output save 2 weeks of legal review." },
          { title: "Open-source license compatibility scanner for African dev teams", why: "Teams ship MVPs with mixed-license code that blocks future commercial moves; a CI check catches it early." },
        ],
        localExamples: ["Filing a Kenyan utility model on a maize sheller", "Ghanaian fintech launching into NDPR + GDPR simultaneously", "Ethiopian software firm licensing AGPL components"],
        careerRoles: ["IP attorney", "Patent agent", "Privacy counsel", "Tech-policy researcher"],
        suggestedVentureSeed: "ARIPO/OAPI prior-art search engine paired with a one-page filing-feasibility report for African inventors.",
      },
      {
        id: "international-law",
        name: "International & Human Rights Law",
        programs: [
          { id: "llb-int", name: "LLB (International focus)", level: "Undergraduate" },
          { id: "llm-int", name: "LLM International Law", level: "Postgraduate" },
        ],
        relevantSectors: ["Governance"],
        relevantTracks: ["ai-for-your-field", "venture-building"],
        relevantAgents: ["regulator-prep", "diligence-prep"],
        relevantProblemIds: [],
        relevantMentorExpertise: ["International law", "Human rights", "Refugee law", "Diplomacy"],
        aiOpportunities: [
          { title: "Refugee-status documentation assistant in 6 languages", why: "Kakuma/Dadaab residents wait years partly because case files are incomplete; guided intake cuts the error rate." },
          { title: "AfCFTA tariff lookup for SMEs crossing borders", why: "The continent's free-trade promise breaks at the customs counter; a tool that knows the schedules unlocks small-trader exports." },
          { title: "Treaty-monitoring dashboard for civil-society organizations", why: "State reports under UN treaty bodies are tracked manually; structured extraction lets advocates ask sharper questions." },
        ],
        localExamples: ["Refugee documentation in Kakuma", "SME exporter learning AFCFTA rules in Accra", "Dual-citizenship application from Lagos"],
        careerRoles: ["International lawyer", "UN agency officer", "Diplomatic service", "Refugee advocate"],
        suggestedVentureSeed: "AfCFTA tariff + documentation walkthrough for SMEs shipping across 2-3 African borders.",
      },
    ],
  },
  {
    id: "humanities",
    name: "School of Humanities & Social Sciences",
    icon: "📚",
    color: "amber",
    departments: [
      {
        id: "education",
        name: "Education",
        programs: [
          { id: "bed", name: "BEd / Bachelor of Education", level: "Undergraduate" },
          { id: "med", name: "Master of Education", level: "Postgraduate" },
          { id: "phd-edu", name: "PhD Education", level: "Postgraduate" },
        ],
        relevantSectors: ["Education"],
        relevantTracks: ["ai-for-your-field", "venture-building"],
        relevantAgents: ["user-persona", "interview-synthesizer", "lp-writer"],
        relevantProblemIds: ["vernacular-tutoring", "stem-lab-access", "credential-trust"],
        relevantMentorExpertise: ["Edtech", "Cohort design"],
        aiOpportunities: [
          { title: "1:1 tutors in mother-tongue languages", why: "200:1 student-teacher ratios are the norm. Personalized practice is the unlock." },
          { title: "Teacher-assistant agents for grading + feedback", why: "Free teachers from grading; they spend time on the relational work no AI can do." },
          { title: "Adaptive curricula for under-resourced schools", why: "Standard pacing fails 60% of African students. Adaptive routes fix this without new teachers." },
        ],
        localExamples: ["Year-1 calc lecturer with 412 students at UNILAG", "Primary teacher in Karamoja with no textbooks", "Rural tech-class in Bolgatanga"],
        careerRoles: ["Teacher", "Edtech founder", "Curriculum designer", "EdTech advisor"],
        suggestedVentureSeed: "A Twi/Yoruba/Hausa-speaking math tutor that runs on Android Go and works offline-tolerant.",
      },
      {
        id: "history",
        name: "History & African Studies",
        programs: [
          { id: "ba-history", name: "BA History", level: "Undergraduate" },
          { id: "ma-african-studies", name: "MA African Studies", level: "Postgraduate" },
        ],
        relevantSectors: ["Creative", "Education", "Governance"],
        relevantTracks: ["ai-for-your-field", "venture-building"],
        relevantAgents: ["user-persona", "press-release", "brand-kit"],
        relevantProblemIds: ["creative-monetization", "vernacular-tutoring"],
        relevantMentorExpertise: ["Edtech", "Creative economy"],
        aiOpportunities: [
          { title: "Oral history archiving with AI transcription", why: "Elder generations are dying. Voice→text→structured archive at scale preserves memory." },
          { title: "Generative storytelling grounded in local mythology", why: "Anansi, Sundiata, Mwindo — your domain says what's authentic vs appropriated." },
          { title: "Heritage-tourism digital experiences", why: "AR/VR layers on Cape Coast, Lalibela, Great Zimbabwe — your scholarship picks the truths to tell." },
        ],
        localExamples: ["Ghanaian Anansi stories archive", "Yoruba oriki documentation", "Liberation history in Zimbabwe"],
        careerRoles: ["Researcher", "Heritage entrepreneur", "Museum curator", "Documentary producer"],
        suggestedVentureSeed: "AI-aided oral-history archive that captures elder voices in their language and makes them searchable.",
      },
      {
        id: "psychology",
        name: "Psychology",
        programs: [
          { id: "bsc-psych", name: "BSc Psychology", level: "Undergraduate" },
          { id: "msc-clinical", name: "MSc Clinical Psychology", level: "Postgraduate" },
        ],
        relevantSectors: ["Health", "Education"],
        relevantTracks: ["math-mastery", "ai-for-your-field"],
        relevantAgents: ["user-persona", "interview-synthesizer", "test-rig"],
        relevantProblemIds: ["diagnosis-gap", "vernacular-tutoring"],
        relevantMentorExpertise: ["Healthtech"],
        aiOpportunities: [
          { title: "Culturally-grounded mental-health chatbots", why: "Western therapy frameworks don't translate. Local-context CBT is a wide-open frontier." },
          { title: "Behavioral analytics for learning platforms", why: "What you know about motivation + retention is exactly what edtech needs." },
          { title: "Workplace well-being AI for African corporates", why: "Burnout is a rising B2B problem. Localized interventions are valuable." },
        ],
        localExamples: ["Post-conflict trauma in Goma", "Urban anxiety in Lagos professionals", "Adolescent counseling in Nairobi"],
        careerRoles: ["Clinical psychologist", "Mental health founder", "UX researcher", "Behavioral economist"],
        suggestedVentureSeed: "Localized mental-health chatbot for African professionals, in Pidgin/English/French.",
      },
      {
        id: "sociology",
        name: "Sociology & Anthropology",
        programs: [
          { id: "ba-soc", name: "BA Sociology", level: "Undergraduate" },
          { id: "ma-anthro", name: "MA Social Anthropology", level: "Postgraduate" },
        ],
        relevantSectors: ["Governance", "Education"],
        relevantTracks: ["ai-for-your-field", "venture-building"],
        relevantAgents: ["interview-synthesizer", "user-persona"],
        relevantProblemIds: ["governance-procurement"],
        relevantMentorExpertise: ["Research", "Public-sector"],
        aiOpportunities: [
          { title: "Qualitative-coding automation for fieldwork interviews", why: "Africa-focused ethnographers code by hand for months; LLM-assisted thematic coding cuts to days while preserving rigor." },
          { title: "Community-survey design with adaptive question routing", why: "Long-form household surveys lose respondents; ML-routed shorter surveys keep quality up." },
          { title: "Migration-pattern dashboards from anonymized telco data", why: "Census data lags reality; aggregated phone-data analysis surfaces urbanization patterns 5 years earlier." },
        ],
        localExamples: ["Rural-to-urban migration study in Kano", "Land-tenure ethnography in Sidamo", "Refugee-host community study in Bidi Bidi"],
        careerRoles: ["Social researcher", "UX researcher", "Policy analyst", "Impact-eval consultant"],
        suggestedVentureSeed: "Interview-to-insights pipeline for African research orgs — upload transcripts, get themed report in 24h.",
      },
      {
        id: "political-science",
        name: "Political Science & Public Administration",
        programs: [
          { id: "ba-poli", name: "BA Political Science", level: "Undergraduate" },
          { id: "mpa", name: "Master of Public Administration", level: "Postgraduate" },
        ],
        relevantSectors: ["Governance"],
        relevantTracks: ["ai-for-your-field", "venture-building"],
        relevantAgents: ["regulator-prep", "competitive-tear"],
        relevantProblemIds: ["governance-procurement"],
        relevantMentorExpertise: ["Public-sector", "Digital policy"],
        aiOpportunities: [
          { title: "Election-monitoring sentiment dashboards from social + radio", why: "ECOWAS observer missions rely on after-the-fact reports; live multilingual sentiment shifts the response window." },
          { title: "Public-budget transparency tool for local councils", why: "Budgets are published as scanned PDFs; OCR + structured extraction makes them actually usable." },
          { title: "Constituency-service tracker for MPs + their constituents", why: "Most MPs lose elections because they can't show their work; a structured logbook + AI-summarized newsletter changes the math." },
        ],
        localExamples: ["Election monitoring in Sierra Leone 2023", "District budget analysis in Western Kenya", "MP constituency office in Lagos"],
        careerRoles: ["Policy analyst", "Public administrator", "Civic-tech founder", "Political consultant"],
        suggestedVentureSeed: "Constituency-service logbook + AI newsletter generator for MPs, sold to incumbents at $200/month.",
      },
      {
        id: "linguistics",
        name: "Languages & Linguistics",
        programs: [
          { id: "ba-ling", name: "BA Linguistics", level: "Undergraduate" },
          { id: "ma-applied-ling", name: "MA Applied Linguistics", level: "Postgraduate" },
        ],
        relevantSectors: ["Education", "Creative"],
        relevantTracks: ["ai-for-your-field", "venture-building"],
        relevantAgents: ["user-persona", "interview-synthesizer"],
        relevantProblemIds: ["vernacular-tutoring"],
        relevantMentorExpertise: ["Education", "Localization", "AI/ML"],
        aiOpportunities: [
          { title: "Low-resource-language ASR + TTS curation pipelines", why: "Hausa/Twi/Wolof/Amharic still have under-10-hour speech corpora; structured collection + labeling is the bottleneck." },
          { title: "Translation memory + glossary builder for African government services", why: "Citizen services available only in English exclude 60%+ of the population; localization toolchains scale impact." },
          { title: "Diaspora language-learning apps with code-switching support", why: "African diaspora kids learn parents' languages best with code-switching support — Duolingo doesn't model this." },
        ],
        localExamples: ["Hausa ASR for radio transcription", "Twi government-form translation", "Diaspora Yoruba app for UK-Nigerian families"],
        careerRoles: ["Linguist", "Localization lead", "Language-AI founder", "Translator"],
        suggestedVentureSeed: "Crowd-sourced low-resource-language speech corpus tool with built-in payment + QA, sold to LLM labs.",
      },
      {
        id: "philosophy",
        name: "Philosophy & Ethics",
        programs: [
          { id: "ba-phil", name: "BA Philosophy", level: "Undergraduate" },
          { id: "ma-ethics", name: "MA Applied Ethics", level: "Postgraduate" },
        ],
        relevantSectors: ["Governance", "Health"],
        relevantTracks: ["ai-for-your-field", "venture-building"],
        relevantAgents: ["regulator-prep"],
        relevantProblemIds: [],
        relevantMentorExpertise: ["AI ethics", "Public policy"],
        aiOpportunities: [
          { title: "AI-ethics review-board tooling for African research institutions", why: "Many IRBs lack AI expertise; structured review templates + AI risk scoring keeps standards consistent." },
          { title: "Algorithmic-bias audits for fintech credit-scoring", why: "African neobanks denying women + youth loans for proxy-discrimination reasons; ethical audits with corrective recommendations are valuable." },
          { title: "Curriculum design for ethics in African STEM programs", why: "Most STEM curricula skip ethics or borrow Western frames; Africa-grounded modules are needed and currently underserved." },
        ],
        localExamples: ["IRB review at U of Nairobi for medical AI", "Algorithmic-bias case at a Nigerian neobank", "Ethics curriculum redesign at KNUST"],
        careerRoles: ["AI ethics consultant", "Policy advisor", "Academic researcher", "Compliance officer"],
        suggestedVentureSeed: "AI-bias audit-as-a-service for African fintech, with regulatory-language reports, $5k per engagement.",
      },
    ],
  },
  {
    id: "sciences",
    name: "College of Pure & Applied Sciences",
    icon: "🔬",
    color: "emerald",
    departments: [
      {
        id: "biology",
        name: "Biological Sciences",
        programs: [
          { id: "bsc-bio", name: "BSc Biology / Zoology / Botany", level: "Undergraduate" },
          { id: "msc-microbio", name: "MSc Microbiology", level: "Postgraduate" },
        ],
        relevantSectors: ["Health", "Agriculture", "Climate"],
        relevantTracks: ["stem-intuition", "math-mastery", "ai-for-your-field", "venture-building"],
        relevantAgents: ["patent-search", "test-rig", "competitive-tear"],
        relevantProblemIds: ["diagnosis-gap", "water-quality", "climate-adaptation"],
        relevantMentorExpertise: ["Healthtech", "Agribusiness"],
        aiOpportunities: [
          { title: "Phone-camera microscopy for malaria/TB", why: "Cheap optics + ML reach diagnostic-grade accuracy. Your bio depth labels the data." },
          { title: "Biodiversity monitoring with bioacoustics", why: "Audio + ML identifies species at scale. Conservation funding loves measurable outcomes." },
          { title: "Soil-microbiome diagnostics for smallholders", why: "Cheap soil tests + ML recommend exact inputs. Yield jumps follow." },
        ],
        localExamples: ["Cassava mosaic disease in Kogi", "Malaria mapping in Eastern Uganda", "Soil testing for cocoa farmers"],
        careerRoles: ["Lab scientist", "Biotech founder", "Conservation tech engineer", "AgroTech advisor"],
        suggestedVentureSeed: "Phone-microscope malaria diagnostic kit — $2 hardware, ML-graded, CHW-friendly.",
      },
      {
        id: "chemistry",
        name: "Chemistry",
        programs: [
          { id: "bsc-chem", name: "BSc Chemistry", level: "Undergraduate" },
          { id: "msc-anchem", name: "MSc Analytical Chemistry", level: "Postgraduate" },
        ],
        relevantSectors: ["Water", "Health", "Agriculture"],
        relevantTracks: ["stem-intuition", "math-mastery", "ai-for-your-field"],
        relevantAgents: ["patent-search", "test-rig"],
        relevantProblemIds: ["water-quality", "diagnosis-gap"],
        relevantMentorExpertise: ["Healthtech", "Agribusiness"],
        aiOpportunities: [
          { title: "Colorimetric water-quality kits + phone vision", why: "$0.10 strip + phone camera = E. coli / fluoride / arsenic readout for any borehole." },
          { title: "Counterfeit fertilizer detection", why: "30% of fertilizer sold is fake. Spectroscopy + ML catches it at the point of sale." },
          { title: "Drug-purity scanning for chemists", why: "Pharmacy operators need quick verification. Handheld + ML." },
        ],
        localExamples: ["Borehole testing in Malawi", "Fertilizer fraud in Nigeria", "Drug counterfeit in Aba"],
        careerRoles: ["Analytical chemist", "Water-tech founder", "QA lead", "Pharma scientist"],
        suggestedVentureSeed: "Colorimetric strip + phone-vision water quality tester for $1, deployable by community health workers.",
      },
      {
        id: "math",
        name: "Mathematics & Statistics",
        programs: [
          { id: "bsc-math", name: "BSc Mathematics / Statistics", level: "Undergraduate" },
          { id: "msc-stats", name: "MSc Statistics / Data Science", level: "Postgraduate" },
        ],
        relevantSectors: ["Finance", "Health", "Climate", "Logistics"],
        relevantTracks: ["math-mastery", "coding-craft", "ai-for-your-field", "venture-building"],
        relevantAgents: ["financial-model", "test-rig", "code-review", "market-sizing"],
        relevantProblemIds: ["smb-bookkeeping", "climate-adaptation", "logistics-last-mile"],
        relevantMentorExpertise: ["Engineering culture", "Fintech"],
        aiOpportunities: [
          { title: "Optimization for logistics on African roads", why: "Last-mile in Lagos is a math problem with poor tools. Your OR depth ships value." },
          { title: "Causal inference for development programs", why: "RCT-graded answers without RCT prices. Funders love measurable impact." },
          { title: "Statistical surveillance for outbreaks", why: "Bayesian early-warning beats CDC-style hindcasting." },
        ],
        localExamples: ["Lagos delivery routing", "Cash-transfer impact in Turkana", "Cholera surveillance"],
        careerRoles: ["Data scientist", "Quant analyst", "Research-to-product founder", "ML engineer"],
        suggestedVentureSeed: "OR-driven routing optimizer for African last-mile delivery — cuts delivery cost 50%.",
      },
      {
        id: "physics",
        name: "Physics & Astronomy",
        programs: [
          { id: "bsc-phys", name: "BSc Physics", level: "Undergraduate" },
          { id: "msc-applied-phys", name: "MSc Applied Physics", level: "Postgraduate" },
        ],
        relevantSectors: ["Energy", "Climate"],
        relevantTracks: ["stem-intuition", "ai-for-your-field", "venture-building"],
        relevantAgents: ["financial-model", "test-rig"],
        relevantProblemIds: ["climate-adaptation"],
        relevantMentorExpertise: ["Energy", "Research", "Hardware"],
        aiOpportunities: [
          { title: "Solar-irradiance forecasting at neighborhood scale for mini-grids", why: "Mini-grid operators size to worst case + overspend; 24h forecasts save 15-20% on storage." },
          { title: "Wind-resource prospecting using public satellite + ML", why: "Wind-resource maps are coarse + expensive; cheap LSTM models on ERA5 + sparse mast data are competitive." },
          { title: "SKA-Africa pipeline tooling for astronomical signal processing", why: "South Africa's MeerKAT/SKA programs generate petabytes; ML pipelines built locally retain talent + IP." },
        ],
        localExamples: ["Mini-grid in Kalangala, Uganda", "Wind survey in Lake Turkana", "MeerKAT data processing"],
        careerRoles: ["Research physicist", "Energy modeler", "Hardware founder", "Data scientist"],
        suggestedVentureSeed: "Neighborhood-scale solar forecast API for African mini-grid operators, $50/month/site.",
      },
      {
        id: "geology",
        name: "Geology & Earth Sciences",
        programs: [
          { id: "bsc-geo", name: "BSc Geology", level: "Undergraduate" },
          { id: "msc-hydro", name: "MSc Hydrogeology", level: "Postgraduate" },
        ],
        relevantSectors: ["Water", "Energy", "Climate"],
        relevantTracks: ["stem-intuition", "ai-for-your-field", "venture-building"],
        relevantAgents: ["test-rig", "financial-model"],
        relevantProblemIds: ["water-quality", "climate-adaptation"],
        relevantMentorExpertise: ["Mining", "Energy", "Water"],
        aiOpportunities: [
          { title: "Groundwater-potential mapping from satellite + spectral data", why: "NGOs drill dry boreholes at $10k each; predictive maps slash failure rate." },
          { title: "Slope-stability monitoring for artisanal mining + rural roads", why: "Landslide deaths in DRC + Cameroon are predictable; phone-photo time-series + ML flag risk." },
          { title: "Soil-quality drone surveys for African farm cooperatives", why: "Cooperative buying clubs can fund $50/acre soil maps; targeted fertilizer cuts costs 30%." },
        ],
        localExamples: ["Borehole siting in West Pokot", "Slope monitoring in Bafoussam", "Cocoa-soil mapping in Western Region"],
        careerRoles: ["Hydrogeologist", "Mining engineer", "Environmental consultant", "Cleantech founder"],
        suggestedVentureSeed: "Pre-drill groundwater potential report for NGOs + drillers, satellite + ML, $200/site.",
      },
      {
        id: "biotech",
        name: "Biotechnology & Biochemistry",
        programs: [
          { id: "bsc-biochem", name: "BSc Biochemistry", level: "Undergraduate" },
          { id: "msc-biotech", name: "MSc Biotechnology", level: "Postgraduate" },
        ],
        relevantSectors: ["Health", "Agriculture"],
        relevantTracks: ["stem-intuition", "ai-for-your-field", "venture-building"],
        relevantAgents: ["test-rig", "regulator-prep"],
        relevantProblemIds: ["chw-diagnostics", "post-harvest-loss"],
        relevantMentorExpertise: ["Diagnostics", "Agritech", "Research"],
        aiOpportunities: [
          { title: "Low-cost LAMP/CRISPR diagnostic protocols for African pathogens", why: "Sequencing capacity is growing; rapid lateral-flow protocols for local pathogens unlock decentralized testing." },
          { title: "Indigenous-crop genetic-marker screening tools", why: "African cassava + sorghum genetics are under-explored; cheap marker tools accelerate breeding." },
          { title: "Probiotic + biocontrol production for smallholder farms", why: "Imported agri-inputs are expensive; locally-produced biocontrols compete on price and on relevance." },
        ],
        localExamples: ["LAMP diagnostic for Lassa fever in Edo", "Cassava breeding at IITA", "Probiotic production for Kenyan smallholders"],
        careerRoles: ["Research scientist", "Diagnostics founder", "Bioproduction engineer", "Agritech R&D"],
        suggestedVentureSeed: "On-site LAMP diagnostic kit for cassava mosaic disease, sold to extension officers at $1/test.",
      },
    ],
  },
  {
    id: "agric",
    name: "College of Agriculture & Natural Resources",
    icon: "🌾",
    color: "emerald",
    departments: [
      {
        id: "crop-science",
        name: "Crop Science & Horticulture",
        programs: [
          { id: "bsc-crops", name: "BSc Crop Science", level: "Undergraduate" },
          { id: "msc-agronomy", name: "MSc Agronomy", level: "Postgraduate" },
        ],
        relevantSectors: ["Agriculture", "Climate"],
        relevantTracks: ["stem-intuition", "ai-for-your-field", "venture-building"],
        relevantAgents: ["market-sizing", "test-rig", "interview-synthesizer"],
        relevantProblemIds: ["post-harvest-loss", "climate-adaptation"],
        relevantMentorExpertise: ["Agribusiness", "Food systems"],
        aiOpportunities: [
          { title: "Vision-based crop disease detection", why: "Your domain knowledge tells the model what to look for." },
          { title: "Variety-trial dashboards for breeders", why: "Marker-assisted breeding tools accelerate cassava, sorghum, millet development." },
          { title: "Precision-input recommendations from soil + weather", why: "What/when/how-much, delivered as a voice note." },
        ],
        localExamples: ["Cassava mosaic in Kogi", "Cocoa swollen shoot in Western Ghana", "Maize lethal necrosis in Kenya"],
        careerRoles: ["Agronomist", "Breeder", "Agritech founder", "AGRA program officer"],
        suggestedVentureSeed: "Voice-note advisory service for smallholders, grounded in local soil + weather data.",
      },
      {
        id: "animal-science",
        name: "Animal Science / Veterinary",
        programs: [
          { id: "bsc-animal", name: "BSc Animal Science", level: "Undergraduate" },
          { id: "dvm", name: "DVM Veterinary Medicine", level: "Both" },
        ],
        relevantSectors: ["Agriculture", "Health"],
        relevantTracks: ["ai-for-your-field"],
        relevantAgents: ["competitive-tear", "test-rig", "interview-synthesizer"],
        relevantProblemIds: ["climate-adaptation"],
        relevantMentorExpertise: ["Agribusiness", "Healthtech"],
        aiOpportunities: [
          { title: "Phone-camera mastitis detection for dairy", why: "Photo + ML catches infection before milk yield drops." },
          { title: "Livestock-disease surveillance via SMS reports", why: "Outbreak alerts from kraal to ministry in hours, not weeks." },
          { title: "Vaccine cold-chain integrity for vets", why: "Same problem as human vaccines; smaller market but high-leverage." },
        ],
        localExamples: ["Pastoralist herds in Turkana", "Poultry hatcheries in Ibadan", "Rift Valley dairy"],
        careerRoles: ["Veterinarian", "Livestock-tech founder", "Animal nutritionist", "Field epidemiologist"],
        suggestedVentureSeed: "Mobile dairy clinic + AI mastitis detection for smallholder dairy cooperatives.",
      },
      {
        id: "food-science",
        name: "Food Science & Nutrition",
        programs: [
          { id: "bsc-food", name: "BSc Food Science", level: "Undergraduate" },
          { id: "msc-nutrition", name: "MSc Nutrition & Dietetics", level: "Postgraduate" },
        ],
        relevantSectors: ["Agriculture", "Health"],
        relevantTracks: ["stem-intuition", "ai-for-your-field", "venture-building"],
        relevantAgents: ["test-rig", "regulator-prep", "interview-synthesizer"],
        relevantProblemIds: ["post-harvest-loss", "chw-diagnostics"],
        relevantMentorExpertise: ["Food systems", "Agribusiness", "Public health"],
        aiOpportunities: [
          { title: "Shelf-life prediction for African processed foods", why: "Most SME food brands guess shelf-life and lose 15-25% to spoilage; sensor + ML predictions cut waste." },
          { title: "Personalized nutrition coaching using local food databases", why: "Western apps don't know millet, fonio, ugali; localized databases + AI coaching is uniquely African." },
          { title: "Allergen + label-compliance checker for African export brands", why: "EU + US import rules trip up African food exporters; AI checker prevents costly rejections." },
        ],
        localExamples: ["Local hot-sauce brand in Accra entering UK retail", "Millet baby-food startup in Niamey", "School-feeding program in Bujumbura"],
        careerRoles: ["Food scientist", "Nutritionist", "Food-tech founder", "Quality assurance manager"],
        suggestedVentureSeed: "EU/US export-compliance checklist + label generator for African food brands, $200/SKU.",
      },
      {
        id: "forestry",
        name: "Forestry & Environmental Science",
        programs: [
          { id: "bsc-forest", name: "BSc Forestry", level: "Undergraduate" },
          { id: "msc-env", name: "MSc Environmental Science", level: "Postgraduate" },
        ],
        relevantSectors: ["Climate", "Agriculture"],
        relevantTracks: ["stem-intuition", "ai-for-your-field", "venture-building"],
        relevantAgents: ["test-rig", "financial-model"],
        relevantProblemIds: ["climate-adaptation"],
        relevantMentorExpertise: ["Climate", "Impact investing", "Agribusiness"],
        aiOpportunities: [
          { title: "Carbon-credit MRV (measurement-reporting-verification) for African reforestation", why: "Voluntary carbon market needs credible MRV; satellite + drone + AI brings unit cost down 10x." },
          { title: "Deforestation early-warning for community forest reserves", why: "Forest rangers patrol blind; satellite-change alerts via SMS unlock community-led enforcement." },
          { title: "Agroforestry species-recommendation tool for smallholders", why: "Local-context tree species + intercrop combos are buried in journals; an accessible tool spreads the knowledge." },
        ],
        localExamples: ["Carbon project in Mau Forest, Kenya", "Community forest in West Region, Cameroon", "Agroforestry pilot in Tigray"],
        careerRoles: ["Forester", "Environmental consultant", "Climate-tech founder", "Conservation officer"],
        suggestedVentureSeed: "Carbon-MRV-as-a-service for small African reforestation projects, $/tonne-verified pricing.",
      },
      {
        id: "fisheries",
        name: "Fisheries & Aquaculture",
        programs: [
          { id: "bsc-fish", name: "BSc Fisheries", level: "Undergraduate" },
          { id: "msc-aqua", name: "MSc Aquaculture", level: "Postgraduate" },
        ],
        relevantSectors: ["Agriculture", "Climate"],
        relevantTracks: ["stem-intuition", "ai-for-your-field", "venture-building"],
        relevantAgents: ["test-rig", "financial-model"],
        relevantProblemIds: ["climate-adaptation", "water-quality"],
        relevantMentorExpertise: ["Agribusiness", "Food systems"],
        aiOpportunities: [
          { title: "Pond-water-quality monitoring for tilapia/catfish farms", why: "Disease + die-off come from dissolved-O2 + ammonia drift; cheap sensors + alerts cut losses 40%." },
          { title: "Fish-stock assessment for artisanal fisheries from boat-log data", why: "Lake Victoria + Volta + Kainji fisheries collapse from over-harvest; data-driven quotas need local tooling." },
          { title: "Cold-chain monitoring for fish moving from beach to inland market", why: "Half the catch spoils before reaching inland buyers; SMS + sensor system unlocks better prices." },
        ],
        localExamples: ["Tilapia farm in Awgu, Nigeria", "Lake Victoria fishing cooperative in Kisumu", "Cold-chain pilot in Bagamoyo"],
        careerRoles: ["Aquaculture manager", "Marine biologist", "Fisheries officer", "Food-tech founder"],
        suggestedVentureSeed: "Pond-water-quality kit + SMS alert system for tilapia farmers, sold via cooperatives at $30/month.",
      },
    ],
  },
  {
    id: "creative",
    name: "School of Design & Creative Arts",
    icon: "🎨",
    color: "rust",
    departments: [
      {
        id: "design",
        name: "Industrial / Graphic Design",
        programs: [
          { id: "bdes", name: "BA / BDes Design", level: "Undergraduate" },
          { id: "mdes", name: "MA Design", level: "Postgraduate" },
        ],
        relevantSectors: ["Creative", "Education"],
        relevantTracks: ["coding-craft", "ai-for-your-field", "venture-building"],
        relevantAgents: ["brand-kit", "lp-writer", "user-persona"],
        relevantProblemIds: ["creative-monetization", "vernacular-tutoring"],
        relevantMentorExpertise: ["Marketplace dynamics"],
        aiOpportunities: [
          { title: "Generative kente / Ankara pattern design with rights protection", why: "Designers' instincts curate good patterns; AI scales without theft." },
          { title: "Low-literacy UX kits for African apps", why: "Most apps assume Western reading order. Pictograms + voice-first patterns are valuable IP." },
          { title: "Brand-on-demand for African SMEs", why: "Hairdressers and tailors need logos. AI-generated + designer-curated wins this market." },
        ],
        localExamples: ["Kente weavers in Bonwire", "Tailor stalls in Yaba market", "Streetwear in Cape Town"],
        careerRoles: ["Industrial designer", "Brand founder", "UI/UX designer", "Creative-tech entrepreneur"],
        suggestedVentureSeed: "AI brand-on-demand subscription for African SMEs — logos, packaging, copy, weekly social.",
      },
      {
        id: "music",
        name: "Music & Performing Arts",
        programs: [
          { id: "bmus", name: "BA / BMus", level: "Undergraduate" },
          { id: "mmus", name: "MA Music", level: "Postgraduate" },
        ],
        relevantSectors: ["Creative"],
        relevantTracks: ["coding-craft", "ai-for-your-field", "venture-building"],
        relevantAgents: ["brand-kit", "press-release", "lp-writer"],
        relevantProblemIds: ["creative-monetization"],
        relevantMentorExpertise: ["Marketplace dynamics"],
        aiOpportunities: [
          { title: "Rights-tracking for streaming royalty leakage", why: "Afrobeats artists lose 90% of royalties to opacity. Audio-fingerprint + on-chain registry fixes this." },
          { title: "AI mastering tuned for Afrobeats / Amapiano", why: "Generic LANDR settings ruin the genre. Local mastering is gold." },
          { title: "Generative beat-making for amateur producers", why: "Lowers barrier without lowering quality. Massive long-tail market." },
        ],
        localExamples: ["Lagos studio session", "Cape Town amapiano DJ", "Highlife royalties in Accra"],
        careerRoles: ["Producer", "Music-tech founder", "A&R", "Rights manager"],
        suggestedVentureSeed: "Audio-fingerprint + smart-royalty platform for Afrobeats artists.",
      },
      {
        id: "architecture",
        name: "Architecture & Urban Planning",
        programs: [
          { id: "bsc-arch", name: "BSc Architecture", level: "Undergraduate" },
          { id: "march", name: "MArch", level: "Postgraduate" },
          { id: "msc-urban", name: "MSc Urban Planning", level: "Postgraduate" },
        ],
        relevantSectors: ["Climate", "Logistics"],
        relevantTracks: ["stem-intuition", "ai-for-your-field", "venture-building"],
        relevantAgents: ["test-rig", "financial-model", "user-persona"],
        relevantProblemIds: ["climate-adaptation"],
        relevantMentorExpertise: ["Architecture", "Urban planning", "Construction tech"],
        aiOpportunities: [
          { title: "Climate-responsive housing-design generator for African cities", why: "Most new construction is concrete oven; AI-generated passive-cooling designs are 30% cheaper to run." },
          { title: "Informal-settlement mapping + upgrading tools for municipalities", why: "Most African cities can't map their own informal areas; drone + AI mapping unlocks service delivery." },
          { title: "BIM-lite for SME contractors with WhatsApp delivery", why: "Building Information Modeling is unaffordable; lightweight phone-driven version brings discipline to small projects." },
        ],
        localExamples: ["Affordable housing pilot in Mukuru, Nairobi", "Climate-resilient build in Maputo coastline", "Informal-settlement upgrading in Kibera"],
        careerRoles: ["Architect", "Urban planner", "Construction-tech founder", "Sustainability consultant"],
        suggestedVentureSeed: "Climate-passive housing-design generator for African SME developers, $200/plot pricing.",
      },
      {
        id: "fashion",
        name: "Fashion & Textile Design",
        programs: [
          { id: "ba-fashion", name: "BA Fashion Design", level: "Undergraduate" },
          { id: "ma-textile", name: "MA Textile Design", level: "Postgraduate" },
        ],
        relevantSectors: ["Creative", "Agriculture"],
        relevantTracks: ["venture-building", "ai-for-your-field"],
        relevantAgents: ["user-persona", "competitive-tear", "financial-model"],
        relevantProblemIds: [],
        relevantMentorExpertise: ["Creator economy", "Manufacturing", "Brand strategy"],
        aiOpportunities: [
          { title: "Made-to-measure pattern-grading from phone photos", why: "African body shapes are underserved by Western size charts; phone-measured patterns unlock fit at scale." },
          { title: "Textile-defect detection at small weaving cooperatives", why: "Adire + Kente cooperatives lose to QC inconsistency; phone-camera AI ensures export-grade quality." },
          { title: "Sustainability + provenance certificates for African textile exports", why: "EU buyers will pay 20% premium for provenance; on-chain certificates with field-data backing capture it." },
        ],
        localExamples: ["Adire cooperative in Abeokuta exporting to UK", "Kente weaver in Bonwire", "Made-to-measure tailor in Dakar"],
        careerRoles: ["Fashion designer", "Textile entrepreneur", "Supply-chain founder", "Sustainability consultant"],
        suggestedVentureSeed: "Phone-measured made-to-measure platform connecting African tailors to global diaspora buyers.",
      },
      {
        id: "industrial-design",
        name: "Industrial & Product Design",
        programs: [
          { id: "bsc-id", name: "BSc Industrial Design", level: "Undergraduate" },
          { id: "ma-pd", name: "MA Product Design", level: "Postgraduate" },
        ],
        relevantSectors: ["Agriculture", "Energy", "Health"],
        relevantTracks: ["stem-intuition", "venture-building", "ai-for-your-field"],
        relevantAgents: ["test-rig", "user-persona", "financial-model"],
        relevantProblemIds: ["post-harvest-loss", "chw-diagnostics"],
        relevantMentorExpertise: ["Hardware", "Manufacturing", "Design thinking"],
        aiOpportunities: [
          { title: "Generative design for low-cost agricultural tools", why: "Cassava graters, palm-oil presses — most are imported and over-engineered; local generative designs cut cost 60%." },
          { title: "Packaging optimization for African SME food brands", why: "Smart packaging design extends shelf-life + reduces transport breakage by 30%." },
          { title: "Off-grid medical-device industrial design", why: "Devices for rural African clinics need ruggedization + power-resilience; designers with that intuition are rare and valuable." },
        ],
        localExamples: ["Cassava grater redesign in Calabar", "Solar-powered fridge for rural clinic in Mozambique", "SME juice-bottle packaging in Lusaka"],
        careerRoles: ["Industrial designer", "Hardware founder", "Packaging engineer", "Product designer"],
        suggestedVentureSeed: "Generative-design service for African agri-tool manufacturers — $500 per tool design, optimized for local materials.",
      },
    ],
  },
  {
    id: "comm",
    name: "School of Communications & Media",
    icon: "📡",
    color: "indigo",
    departments: [
      {
        id: "journalism",
        name: "Journalism & Media Studies",
        programs: [
          { id: "ba-journo", name: "BA Journalism", level: "Undergraduate" },
          { id: "ma-comm", name: "MA Communications", level: "Postgraduate" },
        ],
        relevantSectors: ["Governance", "Creative"],
        relevantTracks: ["coding-craft", "ai-for-your-field", "venture-building"],
        relevantAgents: ["press-release", "competitive-tear", "user-persona"],
        relevantProblemIds: ["governance-procurement", "vernacular-tutoring"],
        relevantMentorExpertise: ["Digital policy", "Public-sector"],
        aiOpportunities: [
          { title: "Investigative-journalism toolkits with document AI", why: "OCR + LLM on leaked PDFs surfaces corruption faster than any newsroom can read." },
          { title: "Multilingual news distillation for diaspora", why: "Local-language summaries of major reporting reach audiences English misses." },
          { title: "Misinformation detection for African elections", why: "Fact-check + ML + community is the only thing that works at WhatsApp scale." },
        ],
        localExamples: ["Premium Times procurement leaks", "Cape election misinformation cycle", "Daily Nation investigations"],
        careerRoles: ["Investigative journalist", "Media founder", "Newsroom data lead", "Content strategist"],
        suggestedVentureSeed: "Whatsapp-distributed misinfo-flagging bot for elections, in the major languages of your country.",
      },
      {
        id: "public-relations",
        name: "Public Relations & Strategic Communications",
        programs: [
          { id: "ba-pr", name: "BA Public Relations", level: "Undergraduate" },
          { id: "ma-strat-comm", name: "MA Strategic Communications", level: "Postgraduate" },
        ],
        relevantSectors: ["Creative", "Governance"],
        relevantTracks: ["venture-building", "ai-for-your-field"],
        relevantAgents: ["press-release", "user-persona", "competitive-tear"],
        relevantProblemIds: ["credential-trust"],
        relevantMentorExpertise: ["Brand strategy", "Crisis communications"],
        aiOpportunities: [
          { title: "Crisis-comms playbook generator for African brands", why: "Most SMEs handle social-media crises ad-hoc; a guided playbook drops response time from days to hours." },
          { title: "Multilingual press-release drafting (English ↔ French ↔ local)", why: "Pan-African comms still happens in English-only; instant translations + cultural-tone checks open continental reach." },
          { title: "Reputation-monitoring across WhatsApp + Twitter + radio call-ins", why: "African brand sentiment lives outside Western social-listening tools; specialized scrapers + analysis open a gap." },
        ],
        localExamples: ["Telco service-outage communications in Lagos", "Banking-fraud crisis response in Accra", "Startup launch press kit for a Nairobi seed round"],
        careerRoles: ["PR lead", "Communications director", "Crisis manager", "Brand strategist"],
        suggestedVentureSeed: "Crisis-comms drafting assistant for African SMEs — one-page playbook in 10 minutes for $20.",
      },
      {
        id: "digital-media",
        name: "Digital Media & Content Production",
        programs: [
          { id: "ba-digital", name: "BA Digital Media", level: "Undergraduate" },
          { id: "ma-multimedia", name: "MA Multimedia Production", level: "Postgraduate" },
        ],
        relevantSectors: ["Creative", "Education"],
        relevantTracks: ["coding-craft", "ai-for-your-field", "venture-building"],
        relevantAgents: ["press-release", "user-persona", "competitive-tear"],
        relevantProblemIds: ["vernacular-tutoring"],
        relevantMentorExpertise: ["Content production", "Creator economy"],
        aiOpportunities: [
          { title: "Short-form video editing automated to local-language captioning", why: "African creators spend 60% of production time on captioning; AI cuts it to seconds and unlocks weekly cadence." },
          { title: "Voice-cloned narration in mother-tongue accents", why: "Authentic local voices for ad/explainer content unlocks 10x reach for SMEs that can't afford studios." },
          { title: "Asset-library generator for African e-commerce", why: "Stock photos rarely show African customers; on-demand local imagery solves a real conversion blocker." },
        ],
        localExamples: ["TikTok creator in Kumasi growing 50k → 500k followers", "Nairobi YouTube cooking channel monetizing", "Mzansi short-form documentary distribution"],
        careerRoles: ["Content producer", "Creator-economy founder", "Brand video editor", "Social-media strategist"],
        suggestedVentureSeed: "Auto-captioning + voice-clone tool fine-tuned for West/East African languages, $/minute pricing.",
      },
      {
        id: "broadcasting",
        name: "Broadcasting & Film Production",
        programs: [
          { id: "ba-film", name: "BA Film & Broadcasting", level: "Undergraduate" },
          { id: "ma-prod", name: "MA Film Production", level: "Postgraduate" },
        ],
        relevantSectors: ["Creative"],
        relevantTracks: ["coding-craft", "ai-for-your-field", "venture-building"],
        relevantAgents: ["press-release", "user-persona"],
        relevantProblemIds: [],
        relevantMentorExpertise: ["Film production", "Distribution", "Streaming"],
        aiOpportunities: [
          { title: "Pre-production scripting + storyboarding for low-budget African film", why: "Nollywood/Riverwood pace demands 7-10 day pre-production; AI assist cuts script-to-shoot to 3 days." },
          { title: "Localized dubbing for African film exports", why: "Pan-African distribution requires 6+ language versions; voice-clone + lip-sync makes this affordable." },
          { title: "Music-rights clearance assistant for streaming uploads", why: "Independent African filmmakers lose YouTube monetization to bad music licensing; a checker prevents takedowns." },
        ],
        localExamples: ["Nollywood feature in 14-day shoot in Lagos", "Documentary on artisanal mining in DRC", "Short film festival submission from Accra"],
        careerRoles: ["Film director", "Producer", "Broadcasting engineer", "Distribution executive"],
        suggestedVentureSeed: "Pre-production assistant (script polish + shot list + budget) for African indie filmmakers at $50/project.",
      },
    ],
  },
];

export function getDepartment(id: string): { department: Department; school: School } | null {
  for (const s of SCHOOLS) {
    const d = s.departments.find((x) => x.id === id);
    if (d) return { department: d, school: s };
  }
  return null;
}

export function getSchool(id: string) {
  return SCHOOLS.find((s) => s.id === id);
}

export function allDepartments(): Array<Department & { schoolName: string; schoolColor: string }> {
  return SCHOOLS.flatMap((s) => s.departments.map((d) => ({ ...d, schoolName: s.name, schoolColor: s.color })));
}
