export type Funding = {
  id: string;
  name: string;
  type: "Grant" | "Accelerator" | "Pre-seed VC" | "Seed VC" | "Series A+" | "Competition" | "Scholarship" | "Debt";
  org: string;
  amountMinUsd: number;
  amountMaxUsd: number;
  equityPct?: number;
  stage: ("Idea" | "MVP" | "Revenue" | "Growth")[];
  sectors: string[];
  geo: string[];
  deadline?: string; // ISO
  rolling: boolean;
  applicationUrl: string;
  description: string;
  whoFor: string;
  signal: 1 | 2 | 3 | 4 | 5; // selectivity/prestige
};

export const FUNDING: Funding[] = [
  {
    id: "yc-summer",
    name: "Y Combinator",
    type: "Accelerator",
    org: "Y Combinator",
    amountMinUsd: 500_000,
    amountMaxUsd: 500_000,
    equityPct: 7,
    stage: ["Idea", "MVP", "Revenue"],
    sectors: ["Any"],
    geo: ["Global"],
    rolling: true,
    applicationUrl: "https://ycombinator.com/apply",
    description: "$500k SAFE on standard YC terms. Three-month intensive in SF, then Demo Day. Accepts 30-40 African startups per batch in recent cycles.",
    whoFor: "Founders with a working prototype or early traction and a willingness to relocate for 3 months.",
    signal: 5,
  },
  {
    id: "techstars-toronto",
    name: "Techstars Toronto (Africa Track)",
    type: "Accelerator",
    org: "Techstars",
    amountMinUsd: 120_000,
    amountMaxUsd: 120_000,
    equityPct: 6,
    stage: ["MVP", "Revenue"],
    sectors: ["Fintech", "Healthtech", "Climate", "AI"],
    geo: ["Africa", "Global"],
    rolling: false,
    deadline: "2026-08-15",
    applicationUrl: "https://techstars.com/apply",
    description: "Three-month program, mentor-driven. African founders heavily featured in recent cohorts.",
    whoFor: "Teams of 2+, MVP shipped, some traction.",
    signal: 5,
  },
  {
    id: "afretech",
    name: "AfreximBank AfricTech Fund",
    type: "Series A+",
    org: "Afreximbank",
    amountMinUsd: 1_000_000,
    amountMaxUsd: 5_000_000,
    stage: ["Revenue", "Growth"],
    sectors: ["Fintech", "Logistics", "Trade", "Climate"],
    geo: ["Africa"],
    rolling: true,
    applicationUrl: "https://afreximbank.com/africtech",
    description: "Patient capital for African scaleups solving intra-African trade friction.",
    whoFor: "Revenue >$50k MRR, clear pan-African expansion thesis.",
    signal: 4,
  },
  {
    id: "tony-elumelu",
    name: "Tony Elumelu Foundation Entrepreneurship Programme",
    type: "Grant",
    org: "Tony Elumelu Foundation",
    amountMinUsd: 5_000,
    amountMaxUsd: 5_000,
    stage: ["Idea", "MVP"],
    sectors: ["Any"],
    geo: ["Africa"],
    rolling: false,
    deadline: "2026-03-31",
    applicationUrl: "https://tefconnect.com",
    description: "$5,000 non-dilutive seed for 10,000 African entrepreneurs annually. 12-week training program.",
    whoFor: "African nationals 18+, business idea or running enterprise.",
    signal: 4,
  },
  {
    id: "agra-accelerator",
    name: "AGRA Centre for African Leaders in Agriculture",
    type: "Grant",
    org: "AGRA",
    amountMinUsd: 25_000,
    amountMaxUsd: 250_000,
    stage: ["MVP", "Revenue"],
    sectors: ["Agriculture", "Food systems"],
    geo: ["East Africa", "West Africa"],
    rolling: false,
    deadline: "2026-06-30",
    applicationUrl: "https://agra.org",
    description: "Catalytic grants for agritech ventures with measurable smallholder impact.",
    whoFor: "Ventures with 6+ months of pilot data with smallholder cooperatives.",
    signal: 4,
  },
  {
    id: "google-black-founders",
    name: "Google for Startups Black Founders Fund (Africa)",
    type: "Grant",
    org: "Google",
    amountMinUsd: 100_000,
    amountMaxUsd: 150_000,
    stage: ["MVP", "Revenue"],
    sectors: ["Any"],
    geo: ["Africa"],
    rolling: false,
    deadline: "2026-04-15",
    applicationUrl: "https://startup.google.com/program/black-founders-fund",
    description: "Non-dilutive cash + Google Cloud credits + hands-on Google mentorship.",
    whoFor: "Black-led African startups with traction.",
    signal: 5,
  },
  {
    id: "norrsken22",
    name: "Norrsken22 African Tech Growth Fund",
    type: "Series A+",
    org: "Norrsken Foundation",
    amountMinUsd: 5_000_000,
    amountMaxUsd: 20_000_000,
    stage: ["Growth"],
    sectors: ["Fintech", "Healthtech", "Edtech"],
    geo: ["Africa"],
    rolling: true,
    applicationUrl: "https://norrsken22.com",
    description: "Growth equity for African scaleups doing $2M+ ARR.",
    whoFor: "Series A/B ready with strong unit economics.",
    signal: 5,
  },
  {
    id: "fa-accelerator",
    name: "Future Africa Collective",
    type: "Pre-seed VC",
    org: "Future Africa",
    amountMinUsd: 100_000,
    amountMaxUsd: 250_000,
    equityPct: 8,
    stage: ["MVP", "Revenue"],
    sectors: ["Any"],
    geo: ["Africa"],
    rolling: true,
    applicationUrl: "https://future.africa",
    description: "Mission-driven pre-seed checks with a syndicate of 250+ African operator-angels.",
    whoFor: "Mission-first founders solving real problems with technical defensibility.",
    signal: 4,
  },
  {
    id: "ventures-platform",
    name: "Ventures Platform Fund",
    type: "Pre-seed VC",
    org: "Ventures Platform",
    amountMinUsd: 150_000,
    amountMaxUsd: 500_000,
    equityPct: 10,
    stage: ["MVP"],
    sectors: ["Any"],
    geo: ["West Africa"],
    rolling: true,
    applicationUrl: "https://ventures.africa",
    description: "Lagos-based pre-seed VC with one of the densest founder networks in West Africa.",
    whoFor: "Nigerian / West African founders, technical or domain-expert teams.",
    signal: 4,
  },
  {
    id: "knife-capital",
    name: "Knife Capital Series A",
    type: "Series A+",
    org: "Knife Capital",
    amountMinUsd: 1_000_000,
    amountMaxUsd: 5_000_000,
    stage: ["Revenue", "Growth"],
    sectors: ["B2B SaaS", "Fintech"],
    geo: ["South Africa", "East Africa"],
    rolling: true,
    applicationUrl: "https://knifecap.com",
    description: "South Africa-headquartered Series A VC, deep DACH and SA institutional LP base.",
    whoFor: "African startups with $1M+ ARR and strong B2B unit economics.",
    signal: 4,
  },
  {
    id: "ahl-prize",
    name: "Africa's Business Heroes Prize Competition",
    type: "Competition",
    org: "Jack Ma Foundation",
    amountMinUsd: 50_000,
    amountMaxUsd: 1_500_000,
    stage: ["Revenue", "Growth"],
    sectors: ["Any"],
    geo: ["Africa"],
    rolling: false,
    deadline: "2026-05-30",
    applicationUrl: "https://africabusinessheroes.org",
    description: "$1.5M in non-dilutive prizes, distributed to top 10 finalists annually.",
    whoFor: "African-founded, African-headquartered businesses creating measurable impact.",
    signal: 5,
  },
  {
    id: "mastercard-foundation-scholars",
    name: "Mastercard Foundation Scholars Program",
    type: "Scholarship",
    org: "Mastercard Foundation",
    amountMinUsd: 5_000,
    amountMaxUsd: 60_000,
    stage: ["Idea"],
    sectors: ["Education"],
    geo: ["Africa"],
    rolling: false,
    deadline: "2026-09-30",
    applicationUrl: "https://mastercardfdn.org/all/scholars",
    description: "Full-tuition + stipend for African students at partner universities. Includes entrepreneurship support.",
    whoFor: "Undergraduate or graduate African students with leadership potential.",
    signal: 5,
  },
  {
    id: "shell-foundation-allon",
    name: "All On (Shell Foundation) Energy Access",
    type: "Debt",
    org: "All On / Shell Foundation",
    amountMinUsd: 250_000,
    amountMaxUsd: 2_000_000,
    stage: ["MVP", "Revenue"],
    sectors: ["Energy", "Climate"],
    geo: ["Nigeria"],
    rolling: true,
    applicationUrl: "https://www.all-on.com",
    description: "Patient debt + equity for off-grid energy ventures with verifiable impact.",
    whoFor: "Hardware/distribution-heavy ventures serving rural Nigeria.",
    signal: 4,
  },
  {
    id: "gates-grand-challenges",
    name: "Grand Challenges (Gates Foundation)",
    type: "Grant",
    org: "Bill & Melinda Gates Foundation",
    amountMinUsd: 100_000,
    amountMaxUsd: 1_000_000,
    stage: ["MVP", "Revenue"],
    sectors: ["Health", "Agriculture", "Climate"],
    geo: ["Global South"],
    rolling: false,
    deadline: "2026-07-15",
    applicationUrl: "https://grandchallenges.org",
    description: "Non-dilutive R&D grants for high-impact health and agriculture innovations.",
    whoFor: "Teams with technical defensibility solving a precisely-stated challenge.",
    signal: 5,
  },
  {
    id: "afdb-yei",
    name: "African Development Bank Youth Entrepreneurship Investment Banks",
    type: "Debt",
    org: "AfDB",
    amountMinUsd: 10_000,
    amountMaxUsd: 250_000,
    stage: ["Revenue", "Growth"],
    sectors: ["Any"],
    geo: ["Africa"],
    rolling: true,
    applicationUrl: "https://afdb.org/en/topics-and-sectors/initiatives-partnerships",
    description: "Subsidized debt facility for African youth-led enterprises.",
    whoFor: "Founders under 35 with revenue-generating ventures.",
    signal: 3,
  },
  {
    id: "anzisha",
    name: "Anzisha Prize",
    type: "Competition",
    org: "African Leadership Academy",
    amountMinUsd: 12_500,
    amountMaxUsd: 25_000,
    stage: ["Idea", "MVP"],
    sectors: ["Any"],
    geo: ["Africa"],
    rolling: false,
    deadline: "2026-03-15",
    applicationUrl: "https://anzishaprize.org",
    description: "For very young African entrepreneurs (15-22) — non-dilutive cash + 3-year accelerator track.",
    whoFor: "African entrepreneurs aged 15-22 with running ventures.",
    signal: 4,
  },
];

export function getFunding(id: string) {
  return FUNDING.find((f) => f.id === id);
}
