export type Mentor = {
  id: string;
  name: string;
  initials: string;
  role: string;
  org: string;
  city: string;
  country: string;
  expertise: string[];
  languages: string[];
  bio: string;
  yearsExperience: number;
  pricePerHour: number; // USD, $0 = pro bono
  availability: "high" | "medium" | "low";
  badges: ("YC" | "Endeavor" | "Techstars" | "Africa Top 50" | "Forbes 30" | "Returnee")[];
  responseHrs: number;
  rating: number;
  sessions: number;
};

export const MENTORS: Mentor[] = [
  {
    id: "iyinoluwa-aboyeji",
    name: "Iyinoluwa Aboyeji",
    initials: "IA",
    role: "Co-founder & General Partner",
    org: "Future Africa",
    city: "Lagos",
    country: "Nigeria",
    expertise: ["Fundraising", "Fintech", "Marketplace", "Venture building"],
    languages: ["English", "Yoruba"],
    bio: "Co-founded Andela and Flutterwave. Now invests in Africa's mission-driven founders. Will be brutally direct on whether your venture has a wedge.",
    yearsExperience: 14,
    pricePerHour: 0,
    availability: "low",
    badges: ["Forbes 30", "Africa Top 50"],
    responseHrs: 72,
    rating: 4.9,
    sessions: 87,
  },
  {
    id: "rebecca-enonchong",
    name: "Rebecca Enonchong",
    initials: "RE",
    role: "Founder & CEO",
    org: "AppsTech",
    city: "Douala",
    country: "Cameroon",
    expertise: ["Enterprise software", "Pan-African expansion", "Public-sector"],
    languages: ["English", "French"],
    bio: "Built one of Africa's first global software companies. AfriLabs chair. Speaks plainly about scaling across 54 jurisdictions.",
    yearsExperience: 24,
    pricePerHour: 0,
    availability: "medium",
    badges: ["Africa Top 50"],
    responseHrs: 48,
    rating: 4.8,
    sessions: 142,
  },
  {
    id: "ham-serunjogi",
    name: "Ham Serunjogi",
    initials: "HS",
    role: "CEO & Co-founder",
    org: "Chipper Cash",
    city: "Kampala",
    country: "Uganda",
    expertise: ["Cross-border payments", "Series A-C", "Regulatory navigation"],
    languages: ["English", "Luganda"],
    bio: "Took Chipper from idea to $2B valuation. Will tell you exactly which licenses you need by market 1, 3, 7.",
    yearsExperience: 11,
    pricePerHour: 200,
    availability: "low",
    badges: ["YC", "Forbes 30"],
    responseHrs: 96,
    rating: 5.0,
    sessions: 54,
  },
  {
    id: "ada-osakwe",
    name: "Ada Osakwe",
    initials: "AO",
    role: "Founder",
    org: "Agrolay Ventures · Nuli",
    city: "Lagos",
    country: "Nigeria",
    expertise: ["Agribusiness", "Food systems", "Impact investing"],
    languages: ["English", "Igbo"],
    bio: "Former senior advisor to Nigeria's Minister of Agriculture. Backs and operates agritech and food brands.",
    yearsExperience: 18,
    pricePerHour: 80,
    availability: "medium",
    badges: ["Endeavor"],
    responseHrs: 48,
    rating: 4.9,
    sessions: 96,
  },
  {
    id: "kennedy-ekezie",
    name: "Kennedy Ekezie",
    initials: "KE",
    role: "CEO",
    org: "Kippa",
    city: "Lagos",
    country: "Nigeria",
    expertise: ["SME fintech", "WhatsApp distribution", "Y Combinator"],
    languages: ["English", "Pidgin"],
    bio: "YC W22. Built one of Nigeria's fastest-growing SME bookkeeping apps. Knows the WhatsApp Cloud API like the back of his hand.",
    yearsExperience: 7,
    pricePerHour: 75,
    availability: "high",
    badges: ["YC"],
    responseHrs: 24,
    rating: 4.7,
    sessions: 213,
  },
  {
    id: "shola-akinlade",
    name: "Shola Akinlade",
    initials: "SA",
    role: "Co-founder & CEO",
    org: "Paystack (acq. Stripe)",
    city: "Lagos",
    country: "Nigeria",
    expertise: ["Payments infrastructure", "Engineering culture", "Acquisitions"],
    languages: ["English", "Yoruba"],
    bio: "Co-founded Paystack, acquired by Stripe for $200M+. Coaches CTOs and engineering-led founders on craft.",
    yearsExperience: 16,
    pricePerHour: 150,
    availability: "low",
    badges: ["YC", "Forbes 30", "Africa Top 50"],
    responseHrs: 96,
    rating: 5.0,
    sessions: 39,
  },
  {
    id: "jessica-mbavarira",
    name: "Jessica Mbavarira",
    initials: "JM",
    role: "Investment Director",
    org: "Norrsken22 African Tech Growth Fund",
    city: "Cape Town",
    country: "South Africa",
    expertise: ["Series B-C fundraising", "Due diligence", "Financial modeling"],
    languages: ["English", "Shona"],
    bio: "Will rip apart your cap table and rebuild it. Specializes in helping African founders prepare for growth-stage US/EU diligence.",
    yearsExperience: 13,
    pricePerHour: 60,
    availability: "high",
    badges: ["Endeavor"],
    responseHrs: 24,
    rating: 4.9,
    sessions: 178,
  },
  {
    id: "tonye-tariah",
    name: "Tonye Tariah",
    initials: "TT",
    role: "Head of Product",
    org: "Andela",
    city: "Nairobi",
    country: "Kenya",
    expertise: ["Product strategy", "Marketplace dynamics", "Talent platforms"],
    languages: ["English", "Swahili"],
    bio: "Shipped products to 100k+ developers across 100 countries. Strong opinions on what 'product-market fit' actually feels like.",
    yearsExperience: 10,
    pricePerHour: 50,
    availability: "high",
    badges: ["Returnee"],
    responseHrs: 12,
    rating: 4.8,
    sessions: 254,
  },
  {
    id: "nneka-okafor",
    name: "Nneka Okafor",
    initials: "NO",
    role: "Founder & CEO",
    org: "Releaf",
    city: "Aba",
    country: "Nigeria",
    expertise: ["Agritech hardware", "Smallholder ops", "YC + Techstars"],
    languages: ["English", "Igbo"],
    bio: "Building palm-oil processing for 4M smallholder farmers. Will help you de-risk hardware-meets-rural-distribution.",
    yearsExperience: 9,
    pricePerHour: 0,
    availability: "medium",
    badges: ["YC", "Techstars"],
    responseHrs: 36,
    rating: 4.9,
    sessions: 91,
  },
  {
    id: "fara-ashiru-jituboh",
    name: "Fara Ashiru Jituboh",
    initials: "FA",
    role: "Co-founder & CTO",
    org: "Okra (acq.)",
    city: "Lagos",
    country: "Nigeria",
    expertise: ["Open banking", "API design", "Hiring senior engineers"],
    languages: ["English"],
    bio: "Built Africa's first open-banking API. Coaches first-time CTOs on architecture choices that don't haunt them later.",
    yearsExperience: 12,
    pricePerHour: 90,
    availability: "medium",
    badges: ["Forbes 30"],
    responseHrs: 36,
    rating: 4.9,
    sessions: 87,
  },
  {
    id: "tayo-oviosu",
    name: "Tayo Oviosu",
    initials: "TO",
    role: "Founder & CEO",
    org: "Paga",
    city: "Lagos",
    country: "Nigeria",
    expertise: ["Mobile money", "Agent networks", "Late-stage fundraising"],
    languages: ["English", "Yoruba"],
    bio: "Built Paga into a 19M-user payments platform. Will walk you through agent-network economics in painful detail.",
    yearsExperience: 17,
    pricePerHour: 120,
    availability: "low",
    badges: ["Africa Top 50"],
    responseHrs: 96,
    rating: 4.8,
    sessions: 46,
  },
  {
    id: "wiebe-boer",
    name: "Wiebe Boer",
    initials: "WB",
    role: "CEO",
    org: "All On (Shell Foundation)",
    city: "Lagos",
    country: "Nigeria",
    expertise: ["Off-grid energy", "Impact financing", "Blended capital"],
    languages: ["English", "Dutch"],
    bio: "Backs renewable-energy ventures across SSA. Knows every blended-finance vehicle that exists. Will introduce you to the right desk.",
    yearsExperience: 22,
    pricePerHour: 0,
    availability: "medium",
    badges: ["Endeavor"],
    responseHrs: 48,
    rating: 4.9,
    sessions: 132,
  },
  {
    id: "dr-rose-mutiso",
    name: "Dr. Rose Mutiso",
    initials: "RM",
    role: "Research Director",
    org: "Energy for Growth Hub",
    city: "Nairobi",
    country: "Kenya",
    expertise: ["Climate policy", "Energy systems", "Research-to-practice"],
    languages: ["English", "Swahili"],
    bio: "PhD MIT materials science. Translates rigorous research into venture-actionable insights for climate-tech founders.",
    yearsExperience: 14,
    pricePerHour: 60,
    availability: "high",
    badges: ["Returnee"],
    responseHrs: 24,
    rating: 4.9,
    sessions: 167,
  },
  {
    id: "vivian-nwakah",
    name: "Vivian Nwakah",
    initials: "VN",
    role: "Founder",
    org: "Medsaf (acq.)",
    city: "Lagos",
    country: "Nigeria",
    expertise: ["Healthtech", "Supply chain", "Exits"],
    languages: ["English", "Igbo"],
    bio: "Sold Medsaf to a strategic acquirer in 2022. Coaches founders through the messy reality of M&A in Africa.",
    yearsExperience: 11,
    pricePerHour: 100,
    availability: "medium",
    badges: ["Forbes 30"],
    responseHrs: 48,
    rating: 4.9,
    sessions: 64,
  },
  {
    id: "kola-aina",
    name: "Kola Aina",
    initials: "KA",
    role: "Founding Partner",
    org: "Ventures Platform",
    city: "Lagos",
    country: "Nigeria",
    expertise: ["Pre-seed/seed", "Founder fit assessment", "Africa-wide network"],
    languages: ["English", "Yoruba"],
    bio: "Backed 70+ African startups. Will tell you in 12 minutes whether you're solving a real problem.",
    yearsExperience: 18,
    pricePerHour: 0,
    availability: "low",
    badges: ["Africa Top 50"],
    responseHrs: 120,
    rating: 5.0,
    sessions: 51,
  },
  {
    id: "tracy-kivunyu",
    name: "Tracy Kivunyu",
    initials: "TK",
    role: "Investment Lead",
    org: "Tofino Capital",
    city: "Nairobi",
    country: "Kenya",
    expertise: ["Diligence", "Term sheet negotiation", "Founder-investor dynamics"],
    languages: ["English", "Swahili"],
    bio: "Coaches founders on how to read the room with US/EU investors. No fluff.",
    yearsExperience: 9,
    pricePerHour: 40,
    availability: "high",
    badges: [],
    responseHrs: 12,
    rating: 4.8,
    sessions: 198,
  },
  {
    id: "prof-bitange-ndemo",
    name: "Prof. Bitange Ndemo",
    initials: "BN",
    role: "Professor & Former PS",
    org: "University of Nairobi",
    city: "Nairobi",
    country: "Kenya",
    expertise: ["Digital policy", "Government navigation", "ICT4D"],
    languages: ["English", "Swahili"],
    bio: "Architect of Kenya's ICT infrastructure boom. Goes deep on regulatory engagement and public-private models.",
    yearsExperience: 30,
    pricePerHour: 0,
    availability: "medium",
    badges: ["Africa Top 50"],
    responseHrs: 72,
    rating: 4.9,
    sessions: 119,
  },
  {
    id: "ange-frederick",
    name: "Ange Frederick Balma",
    initials: "AF",
    role: "Founder",
    org: "LifeBank (CI)",
    city: "Abidjan",
    country: "Côte d'Ivoire",
    expertise: ["Francophone Africa", "Healthtech logistics", "WAEMU markets"],
    languages: ["French", "English"],
    bio: "One of the few francophone West African founders to scale into anglophone markets. Coaches on cross-region playbooks.",
    yearsExperience: 12,
    pricePerHour: 50,
    availability: "high",
    badges: [],
    responseHrs: 18,
    rating: 4.7,
    sessions: 156,
  },
  {
    id: "audrey-cheng",
    name: "Audrey Cheng",
    initials: "AC",
    role: "Co-founder",
    org: "Moringa School",
    city: "Nairobi",
    country: "Kenya",
    expertise: ["Edtech", "Talent placement", "Cohort design"],
    languages: ["English", "Swahili"],
    bio: "Trained 3,000+ developers placed across global tech. Knows the cohort-based-learning playbook inside out.",
    yearsExperience: 11,
    pricePerHour: 60,
    availability: "medium",
    badges: ["Endeavor"],
    responseHrs: 36,
    rating: 4.9,
    sessions: 124,
  },
];

export function getMentor(id: string) {
  return MENTORS.find((m) => m.id === id);
}
