import type { Problem } from "./problems";

// Additional 20 problem briefs across more sectors and regions.
export const PROBLEMS_EXTRA: Problem[] = [
  {
    id: "school-fees-default",
    title: "70% of African parents miss school-fee deadlines — kids sent home weekly",
    region: "Pan-African",
    sector: "Finance",
    severity: 5,
    affected: "150M school-age children across SSA",
    description: "Term fees are a cliff: due in one lump, with no smoothing mechanism. Parents borrow informally, miss deadlines, and children are sent home in front of classmates for days.",
    evidence: "UNESCO Africa Education Cost Survey 2024; ANCEFA roundup 2023.",
    aiAngle: "Income-aware micro-payment schedules + employer-mediated payroll deduction + small no-interest credit line — orchestrated by an LLM that talks to parents in their language.",
    skillsNeeded: ["Fintech", "Payments", "Behavioral econ", "Counselor UX"],
    exampleVentures: ["Sava (NG)", "Edutalim"],
  },
  {
    id: "creator-bank",
    title: "African creators can't open business accounts without a 'real' incorporation",
    region: "Pan-African",
    sector: "Creative",
    severity: 4,
    affected: "5M+ musicians, designers, writers, video producers",
    description: "Sole-trader creators are forced into informal cash; can't accept Stripe/Paystack; brands won't pay them as individuals. The KYC barrier kills monetization.",
    evidence: "GSMA Mobile Money Africa report 2024.",
    aiAngle: "AI-driven 'creator entity in a box' — auto-incorporate in NG/GH/KE, generate compliance docs, open a digital banking line in <10 minutes.",
    skillsNeeded: ["Legaltech", "Banking APIs", "KYC automation"],
  },
  {
    id: "school-stem-labs",
    title: "Secondary schools graduate students who've never done a real experiment",
    region: "Pan-African",
    sector: "Education",
    severity: 5,
    affected: "120M secondary-school students",
    description: "Lab equipment is broken or missing. Even WAEC/KCSE practical exams are done on paper. Graduates entering medical, engineering, science programs are 2+ years behind.",
    evidence: "ADEA practical-skills audit 2023; Senegal MEN baseline 2024.",
    aiAngle: "Browser-based virtual labs (Labster-class) + AR demos via low-cost Android, with AI proctor that grades execution as well as answers.",
    skillsNeeded: ["Physics simulation", "Curriculum design", "AR", "Mobile-first"],
  },
  {
    id: "transport-women-safety",
    title: "8 in 10 African women experience harassment on public transport",
    region: "Urban Africa",
    sector: "Governance",
    severity: 4,
    affected: "200M women commuters",
    description: "From matatus in Nairobi to BRT in Lagos, daily commute is dangerous. Existing reporting tools require literacy, smartphones, and police trust.",
    evidence: "UN Women Cities Safety Audit 2024.",
    aiAngle: "One-tap, voice-activated reporting with anonymous heatmaps that transport authorities and women-led NGOs can act on.",
    skillsNeeded: ["Civic tech", "Women's safety", "Geospatial", "Government partnerships"],
  },
  {
    id: "labour-skill-discovery",
    title: "Informal artisans (welders, tailors, plumbers) are invisible to formal employers",
    region: "Pan-African",
    sector: "Finance",
    severity: 4,
    affected: "120M informal-sector workers",
    description: "Skilled artisans can't show their portfolio digitally. Construction firms, hotels, factories can't find them. The mismatch costs both sides money.",
    evidence: "ILO Informal Economy Africa 2024.",
    aiAngle: "Photo + voice-based portfolio with AI-graded skill demonstrations; matched to formal-sector openings via WhatsApp.",
    skillsNeeded: ["Vision", "Marketplace", "Voice", "Trust UX"],
    exampleVentures: ["Andela (formalized tech)", "Lynk (Kenya)"],
  },
  {
    id: "translation-justice",
    title: "Court cases tried in languages the defendant doesn't speak",
    region: "Pan-African",
    sector: "Governance",
    severity: 5,
    affected: "20M people facing court annually in non-mother-tongue jurisdictions",
    description: "Courts in Cameroon, Mozambique, Kenya, Nigeria conduct proceedings in English/French/Portuguese while defendants speak only local languages.",
    evidence: "Open Society Foundation Justice Africa 2024.",
    aiAngle: "Real-time, in-court LLM translation for the ~30 most spoken African languages; provides defendants a simultaneous transcript in their language.",
    skillsNeeded: ["Low-resource NLP", "Legal expertise", "Voice", "Government partnerships"],
  },
  {
    id: "fertility-uxr",
    title: "1 in 4 African couples face fertility issues — counseling is rare and stigmatized",
    region: "Pan-African",
    sector: "Health",
    severity: 4,
    affected: "8M couples annually",
    description: "Fertility services are sparse, expensive, and culturally taboo. Misinformation thrives. Couples spend years and savings on traditional remedies.",
    evidence: "WHO Reproductive Health Africa 2024.",
    aiAngle: "Confidential, culturally-aware chatbot guidance + ovulation tracking + clinic referral routing.",
    skillsNeeded: ["Healthtech", "Reproductive health", "Cultural counseling", "Privacy UX"],
  },
  {
    id: "drought-insurance",
    title: "Smallholders have no crop insurance — one bad season wipes out savings",
    region: "Sahel + Horn of Africa",
    sector: "Climate",
    severity: 5,
    affected: "60M climate-vulnerable smallholder farmers",
    description: "Index insurance products exist on paper but distribution fails. Claims processes require farm visits that insurers won't pay for.",
    evidence: "IFAD Climate Risk Africa 2024; ACRE Africa briefing 2023.",
    aiAngle: "Satellite-triggered automatic payouts (no claim filing) + parametric insurance + cooperative-level pooling.",
    skillsNeeded: ["Geospatial ML", "Insurance", "Smart contracts", "Cooperative distribution"],
    exampleVentures: ["Pula Advisors", "ACRE Africa"],
  },
  {
    id: "scholarship-discovery",
    title: "Brilliant African students miss scholarships because they can't find them",
    region: "Pan-African",
    sector: "Education",
    severity: 4,
    affected: "11M tertiary students",
    description: "Hundreds of millions in scholarships go unclaimed because the discovery layer is broken. Listings are on outdated PDFs across dozens of foundations.",
    evidence: "Mastercard Foundation Scholars review 2023.",
    aiAngle: "AI scholarship-matching engine that reads the user's transcript and surfaces every relevant open program globally + auto-drafts the application.",
    skillsNeeded: ["Document AI", "Web scraping", "Recommendation systems", "Application writing"],
  },
  {
    id: "warehouse-fraud",
    title: "$8B/year lost to warehouse receipt fraud in African commodity chains",
    region: "West & East Africa",
    sector: "Finance",
    severity: 4,
    affected: "Cocoa, coffee, cashew, maize value chains",
    description: "Bagging fraud, weight manipulation, and ghost receipts plague commodity logistics. Banks won't lend against warehouse receipts because they can't trust them.",
    evidence: "AFEX Africa, IFC reports 2024.",
    aiAngle: "Phone-camera weight + bag verification + on-chain receipt registry. Banks lend confidently; farmers get better prices.",
    skillsNeeded: ["Vision", "Logistics", "Banking", "Cryptography"],
    exampleVentures: ["AFEX Commodities Exchange"],
  },
  {
    id: "art-export",
    title: "African artists can't sell to global collectors — shipping/auth/payments fail",
    region: "Pan-African",
    sector: "Creative",
    severity: 3,
    affected: "200k+ visual artists",
    description: "Authentication, shipping insurance, customs paperwork, FX — each is a wall. Most African contemporary art is sold offline to local buyers at a discount.",
    evidence: "ArtNet Africa 2024 market report.",
    aiAngle: "End-to-end logistics + AI authentication via NFT-style provenance + global collector matching.",
    skillsNeeded: ["Marketplace", "Shipping logistics", "Authentication", "Crypto/escrow"],
  },
  {
    id: "tax-compliance-sme",
    title: "African SMEs spend 200+ hours/year on tax compliance",
    region: "Pan-African",
    sector: "Finance",
    severity: 4,
    affected: "44M SMEs",
    description: "Multi-tier tax (VAT, PAYE, NHIF/NSSF, corporate, withholding) is paperwork-heavy and changes constantly. Most SMEs hire expensive accountants or simply evade.",
    evidence: "PwC Africa Tax Burden 2024; KRA/FIRS reports.",
    aiAngle: "AI accountant that talks to the bookkeeping bot, prepares filings, and submits via revenue-authority APIs automatically.",
    skillsNeeded: ["Tax law", "Conversational AI", "Government APIs", "Accounting"],
  },
  {
    id: "land-registry",
    title: "60% of African urban land has no clear title — disputes paralyze investment",
    region: "Pan-African",
    sector: "Governance",
    severity: 5,
    affected: "300M urban residents",
    description: "Without clear titles, no mortgages, no investment, no inheritance. Disputes clog courts for decades.",
    evidence: "World Bank Land Governance Assessment 2024.",
    aiAngle: "Satellite + crowdsourced + on-chain land registry with AI-mediated dispute resolution suggestions.",
    skillsNeeded: ["Geospatial", "Cryptography", "Legaltech", "Government partnerships"],
  },
  {
    id: "skill-microcert",
    title: "Bootcamp grads can code but can't prove it to recruiters",
    region: "Pan-African",
    sector: "Education",
    severity: 4,
    affected: "1M+ bootcamp graduates annually",
    description: "Bootcamps issue certificates that recruiters discount. Junior developers can't get past the first screen.",
    evidence: "Andela hiring funnel report 2024; Moringa School outcomes.",
    aiAngle: "AI-proctored live coding challenges + portfolio-of-shipped-projects with on-chain attestation + verified employer-network referrals.",
    skillsNeeded: ["AI proctoring", "Cryptography", "Recruiter UX", "Employer relations"],
  },
  {
    id: "media-misinformation",
    title: "WhatsApp misinformation drives election violence and health-crisis deaths",
    region: "Pan-African",
    sector: "Governance",
    severity: 5,
    affected: "All 600M African WhatsApp users",
    description: "Election cycles and disease outbreaks both turn lethal because misinformation spreads at WhatsApp speed. Fact-checking takes hours; rumors take minutes.",
    evidence: "Africa Check 2024 reports; ECONEC observations.",
    aiAngle: "WhatsApp-native fact-checking bot in local languages, returning verdicts in under 60 seconds with sources.",
    skillsNeeded: ["NLP", "Civic tech", "Public health", "Journalism"],
  },
  {
    id: "diaspora-savings",
    title: "Diaspora savings sit in foreign banks earning 0.1% while home economies starve",
    region: "Pan-African",
    sector: "Finance",
    severity: 3,
    affected: "30M Africans in the diaspora",
    description: "Diaspora deposits in their countries' banks could finance infrastructure but trust + FX + regulation kill the flow.",
    evidence: "AfDB Diaspora Bonds Africa 2024.",
    aiAngle: "Trusted diaspora-savings rail with FX hedging, dollar-pegged deposits, and visibility into where capital is deployed.",
    skillsNeeded: ["Banking", "FX", "Bond structuring", "Trust UX"],
  },
  {
    id: "blind-skill",
    title: "Blind and low-vision Africans are 80% unemployed despite high literacy",
    region: "Pan-African",
    sector: "Education",
    severity: 4,
    affected: "26M blind/low-vision Africans",
    description: "Most educational and work platforms are inaccessible. Screen readers don't speak African languages. Braille training is expensive.",
    evidence: "African Disability Forum 2024.",
    aiAngle: "Voice-first work + learning platform in major African languages; AI document narration; voice-driven coding.",
    skillsNeeded: ["Accessibility", "Voice", "Low-resource NLP", "Curriculum design"],
  },
  {
    id: "remittance-receipt",
    title: "Remittance receivers wait 3+ days for funds — many run out of food",
    region: "Pan-African",
    sector: "Finance",
    severity: 4,
    affected: "100M+ remittance-dependent households",
    description: "MoneyGram/WU charge 6-12% AND delay 24-72 hours. Receivers often subsist between transfers.",
    evidence: "World Bank Remittance Prices 2024.",
    aiAngle: "Sub-1% cross-border rail + instant local-currency disbursement via mobile money; risk underwriting via ML on diaspora behavior.",
    skillsNeeded: ["Cross-border payments", "Compliance", "FX hedging", "Mobile money APIs"],
    exampleVentures: ["Sendwave (acq.)", "Lemfi", "Chipper Cash"],
  },
  {
    id: "soil-test",
    title: "Smallholders apply wrong fertilizer mix → 40% yield loss vs precision-applied",
    region: "Pan-African",
    sector: "Agriculture",
    severity: 5,
    affected: "33M smallholder farmers",
    description: "Generic NPK applied across vastly different soils. AGRA studies show precision soil testing + variable rate could 1.4x yields. Tests cost $40 + lab access.",
    evidence: "AGRA Africa Soil Information Service 2024.",
    aiAngle: "$2 phone-imaged soil test with NIR + ML; field-specific variable-rate fertilizer recommendations in voice.",
    skillsNeeded: ["Soil science", "Vision", "Spectroscopy", "Cooperative distribution"],
  },
  {
    id: "school-attendance",
    title: "Rural schools can't reliably track which students are showing up",
    region: "Pan-African",
    sector: "Education",
    severity: 3,
    affected: "70M rural primary-school children",
    description: "Attendance is taken on paper, lost, falsified for grants. Donors can't verify program impact. Truant children fall through the cracks.",
    evidence: "World Bank Service Delivery Indicators 2024.",
    aiAngle: "Face-vector check-in (privacy-preserved) + offline-tolerant device + verified attendance for donor reporting.",
    skillsNeeded: ["Vision", "Edge inference", "Privacy", "Donor reporting"],
  },
];
